//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.DBSCreator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Swedish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Swedish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.DBSCreator.Localization.Swedish", typeof(Localization_Swedish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigerar tabell System version.
        /// </summary>
        internal static string cgpCorrection1 {
            get {
                return ResourceManager.GetString("cgpCorrection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigering av tabell System version misslyckades.
        /// </summary>
        internal static string cgpCorrection1fail {
            get {
                return ResourceManager.GetString("cgpCorrection1fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigering av tabell System version lyckades.
        /// </summary>
        internal static string cgpCorrection1success {
            get {
                return ResourceManager.GetString("cgpCorrection1success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill Ni fortsätta ändå?.
        /// </summary>
        internal static string cgpCorrectionContinueAnyway {
            get {
                return ResourceManager.GetString("cgpCorrectionContinueAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Säkerställ att databasen har korrekt struktur!.
        /// </summary>
        internal static string cgpCorrectionDatabaseHasCorrectStructure {
            get {
                return ResourceManager.GetString("cgpCorrectionDatabaseHasCorrectStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigerar tabeller för versionen.
        /// </summary>
        internal static string cgpCorrectionPart {
            get {
                return ResourceManager.GetString("cgpCorrectionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to misslyckades.
        /// </summary>
        internal static string cgpCorrectionPartFailed {
            get {
                return ResourceManager.GetString("cgpCorrectionPartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lyckades.
        /// </summary>
        internal static string cgpCorrectionPartSucceeded {
            get {
                return ResourceManager.GetString("cgpCorrectionPartSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigerar händelselogg tabeller för version.
        /// </summary>
        internal static string cgpEventlogCorrectionPart {
            get {
                return ResourceManager.GetString("cgpEventlogCorrectionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigerar NCAS tabeller för version.
        /// </summary>
        internal static string cgpNCASCorrection {
            get {
                return ResourceManager.GetString("cgpNCASCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigerar NCAS tabell för version.
        /// </summary>
        internal static string cgpNCASCorrectionPart {
            get {
                return ResourceManager.GetString("cgpNCASCorrectionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortsätt.
        /// </summary>
        internal static string DbsConversion_bContinue {
            get {
                return ResourceManager.GetString("DbsConversion_bContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas konvertering.
        /// </summary>
        internal static string DbsConversionDbsConversion {
            get {
                return ResourceManager.GetString("DbsConversionDbsConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string DbsLogin_bCancel {
            get {
                return ResourceManager.GetString("DbsLogin_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggning.
        /// </summary>
        internal static string DbsLogin_bgDbsLogin {
            get {
                return ResourceManager.GetString("DbsLogin_bgDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DbsLogin_bOk {
            get {
                return ResourceManager.GetString("DbsLogin_bOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas inloggning.
        /// </summary>
        internal static string DbsLogin_gbDbsLogin {
            get {
                return ResourceManager.GetString("DbsLogin_gbDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        internal static string DbsLogin_lName {
            get {
                return ResourceManager.GetString("DbsLogin_lName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        internal static string DbsLogin_lPassword {
            get {
                return ResourceManager.GetString("DbsLogin_lPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa ny inloggning.
        /// </summary>
        internal static string DbsLogin_rbCreateLogin {
            get {
                return ResourceManager.GetString("DbsLogin_rbCreateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anpassad inloggning.
        /// </summary>
        internal static string DbsLogin_rbCustomDbsLogin {
            get {
                return ResourceManager.GetString("DbsLogin_rbCustomDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Använd befintlig inloggning.
        /// </summary>
        internal static string DbsLogin_rbExistLogin {
            get {
                return ResourceManager.GetString("DbsLogin_rbExistLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa nu cgpInloggning.
        /// </summary>
        internal static string DbsLogin_rbGenrateNewCglLogin {
            get {
                return ResourceManager.GetString("DbsLogin_rbGenrateNewCglLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dbs inloggning.
        /// </summary>
        internal static string DbsLoginDbsLogin {
            get {
                return ResourceManager.GetString("DbsLoginDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra inloggning misslyckades..
        /// </summary>
        internal static string ErrorAlterLogin {
            get {
                return ResourceManager.GetString("ErrorAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra användare misslyckades.
        /// </summary>
        internal static string ErrorAlterUserFailed {
            get {
                return ResourceManager.GetString("ErrorAlterUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa användare misslyckades.
        /// </summary>
        internal static string ErrorCreateUserFailed {
            get {
                return ResourceManager.GetString("ErrorCreateUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databasen finns redan.
        /// </summary>
        internal static string ErrorDatabaseAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorDatabaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa mapp för databasen misslyckades.
        /// </summary>
        internal static string ErrorDirectoryCreationFailed {
            get {
                return ResourceManager.GetString("ErrorDirectoryCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange inloggning.
        /// </summary>
        internal static string ErrorEntryLogin {
            get {
                return ResourceManager.GetString("ErrorEntryLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange lösenord.
        /// </summary>
        internal static string ErrorEntryPassword {
            get {
                return ResourceManager.GetString("ErrorEntryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel, extern databas måste vara annan än huvuddatabasen.
        /// </summary>
        internal static string ErrorExternDbsNameEqualToMainDbs {
            get {
                return ResourceManager.GetString("ErrorExternDbsNameEqualToMainDbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misslyckades att skapa ny cgpInloggning .
        /// </summary>
        internal static string ErrorFailedGenerateLogin {
            get {
                return ResourceManager.GetString("ErrorFailedGenerateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login finns redan.
        /// </summary>
        internal static string ErrorLoginAlreadyExist {
            get {
                return ResourceManager.GetString("ErrorLoginAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn ej tillåtet.
        /// </summary>
        internal static string ErrorNameNotAllowed {
            get {
                return ResourceManager.GetString("ErrorNameNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL servern hittades inte eller var inte tillgänglig. Vill Ni köra databas konfiguration?.
        /// </summary>
        internal static string ErrorQuestionSqlServerNotFoundRunDatabaseConfiguration {
            get {
                return ResourceManager.GetString("ErrorQuestionSqlServerNotFoundRunDatabaseConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabell SystemVersion i konfigurationsdatabasen är korrupt.
        /// </summary>
        internal static string ErrorTableSystemVersionInConfigurationDatabaseCorrupted {
            get {
                return ResourceManager.GetString("ErrorTableSystemVersionInConfigurationDatabaseCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabell SystemVersion i händelseloggen är korrupt.
        /// </summary>
        internal static string ErrorTableSystemVersionInEventlogDatabaseCorrupted {
            get {
                return ResourceManager.GetString("ErrorTableSystemVersionInEventlogDatabaseCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord och bekräftat lösenord matchar ej.
        /// </summary>
        internal static string ErrorWrondConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorWrondConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel användarnamn eller lösenord.
        /// </summary>
        internal static string ErrorWrongLoginNameOrPassword {
            get {
                return ResourceManager.GetString("ErrorWrongLoginNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormAlterTables_bCancel {
            get {
                return ResourceManager.GetString("FormAlterTables_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        internal static string FormAlterTables_bListErrors {
            get {
                return ResourceManager.GetString("FormAlterTables_bListErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åtgärda.
        /// </summary>
        internal static string FormAlterTables_bRunAlter {
            get {
                return ResourceManager.GetString("FormAlterTables_bRunAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databasen innehåller oanvända kolumner som inte finns i hbm schemat. Dessa tas bort vid ändring av databas..
        /// </summary>
        internal static string FormAlterTables_eAlterInfo {
            get {
                return ResourceManager.GetString("FormAlterTables_eAlterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändring av databas misslyckades..
        /// </summary>
        internal static string FormAlterTablesAlterDatabaseFailed {
            get {
                return ResourceManager.GetString("FormAlterTablesAlterDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändring av databas slutfördes..
        /// </summary>
        internal static string FormAlterTablesAlterDatabaseFinished {
            get {
                return ResourceManager.GetString("FormAlterTablesAlterDatabaseFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kolumn.
        /// </summary>
        internal static string FormAlterTablesColumn {
            get {
                return ResourceManager.GetString("FormAlterTablesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databasen innehåller fel..
        /// </summary>
        internal static string FormAlterTablesDatabaseConstainErrors {
            get {
                return ResourceManager.GetString("FormAlterTablesDatabaseConstainErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas är OK..
        /// </summary>
        internal static string FormAlterTablesDatabaseOK {
            get {
                return ResourceManager.GetString("FormAlterTablesDatabaseOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändring av databas.
        /// </summary>
        internal static string FormAlterTablesfAlterTables {
            get {
                return ResourceManager.GetString("FormAlterTablesfAlterTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabell.
        /// </summary>
        internal static string FormAlterTablesTable {
            get {
                return ResourceManager.GetString("FormAlterTablesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Bakåt.
        /// </summary>
        internal static string FormBeforeExecution_bBack {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormBeforeExecution_bCancel {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utför.
        /// </summary>
        internal static string FormBeforeExecution_bPerform {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ångra.
        /// </summary>
        internal static string FormBeforeExecution_bUndoDatabase {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bUndoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ångra.
        /// </summary>
        internal static string FormBeforeExecution_bUndoUser {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bUndoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra existerande.
        /// </summary>
        internal static string FormBeforeExecution_cbAlterLogin {
            get {
                return ResourceManager.GetString("FormBeforeExecution_cbAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas:.
        /// </summary>
        internal static string FormBeforeExecution_lDatabase {
            get {
                return ResourceManager.GetString("FormBeforeExecution_lDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        internal static string FormBeforeExecution_lLogin {
            get {
                return ResourceManager.GetString("FormBeforeExecution_lLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pågår:.
        /// </summary>
        internal static string FormBeforeExecution_lProgress {
            get {
                return ResourceManager.GetString("FormBeforeExecution_lProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server:.
        /// </summary>
        internal static string FormBeforeExecution_lSqlServer {
            get {
                return ResourceManager.GetString("FormBeforeExecution_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa tabeller misslyckades.
        /// </summary>
        internal static string FormBeforeExecutionCreationTablesFail {
            get {
                return ResourceManager.GetString("FormBeforeExecutionCreationTablesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa användare misslyckas.
        /// </summary>
        internal static string FormBeforeExecutionCreationUserFail {
            get {
                return ResourceManager.GetString("FormBeforeExecutionCreationUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas avbruten..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseCancelled {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas kan ej skapas..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseCannotByCreated {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseCannotByCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas skapad..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseCreated {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa databas misslyckades..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseCreationFailed {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas finns redan..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseExists {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigör databas misslyckades.
        /// </summary>
        internal static string FormBeforeExecutionDropDatabaseFail {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDropDatabaseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigör användare misslyckas.
        /// </summary>
        internal static string FormBeforeExecutionDropUserFail {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDropUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa databas.
        /// </summary>
        internal static string FormBeforeExecutionfBeforeExecution {
            get {
                return ResourceManager.GetString("FormBeforeExecutionfBeforeExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Färdig.
        /// </summary>
        internal static string FormBeforeExecutionFinished {
            get {
                return ResourceManager.GetString("FormBeforeExecutionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort användaren.
        /// </summary>
        internal static string FormBeforeExecutionQuestionDeleteUser {
            get {
                return ResourceManager.GetString("FormBeforeExecutionQuestionDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigör databas.
        /// </summary>
        internal static string FormBeforeExecutionQuestionDropDatabase {
            get {
                return ResourceManager.GetString("FormBeforeExecutionQuestionDropDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabeller skapade..
        /// </summary>
        internal static string FormBeforeExecutionTablesCreated {
            get {
                return ResourceManager.GetString("FormBeforeExecutionTablesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användare avbröts..
        /// </summary>
        internal static string FormBeforeExecutionUserCancelled {
            get {
                return ResourceManager.GetString("FormBeforeExecutionUserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användare skapad.
        /// </summary>
        internal static string FormBeforeExecutionUserCreated {
            get {
                return ResourceManager.GetString("FormBeforeExecutionUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användare finns.
        /// </summary>
        internal static string FormBeforeExecutionUserExists {
            get {
                return ResourceManager.GetString("FormBeforeExecutionUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Bakåt.
        /// </summary>
        internal static string FormConfirmation_bBack {
            get {
                return ResourceManager.GetString("FormConfirmation_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormConfirmation_bCancel {
            get {
                return ResourceManager.GetString("FormConfirmation_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klar.
        /// </summary>
        internal static string FormConfirmation_bNext {
            get {
                return ResourceManager.GetString("FormConfirmation_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server inställningar.
        /// </summary>
        internal static string FormConfirmationfConfirmation {
            get {
                return ResourceManager.GetString("FormConfirmationfConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationen av SQL Servern är klar..
        /// </summary>
        internal static string FormConfirmationlabel1 {
            get {
                return ResourceManager.GetString("FormConfirmationlabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck på Klar för att skapa databas.
        /// </summary>
        internal static string FormConfirmationlabel2 {
            get {
                return ResourceManager.GetString("FormConfirmationlabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Bakåt.
        /// </summary>
        internal static string FormDatabaseSettings_bBack {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormDatabaseSettings_bCancel {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nästa &gt;.
        /// </summary>
        internal static string FormDatabaseSettings_bNext {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas namn:.
        /// </summary>
        internal static string FormDatabaseSettings_lDatabaseName {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_lDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas inställningar.
        /// </summary>
        internal static string FormDatabaseSettings_lMainInfo {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_lMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sökväg till databasfiler.
        /// </summary>
        internal static string FormDatabaseSettings_lPath {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_lPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server:.
        /// </summary>
        internal static string FormDatabaseSettings_lSqlServer {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server inställningar.
        /// </summary>
        internal static string FormDatabaseSettingsfDatabaseSettings {
            get {
                return ResourceManager.GetString("FormDatabaseSettingsfDatabaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Använd befintlig inloggning (autentiseringsuppgifter kontrolleras först).
        /// </summary>
        internal static string FormDbsLogin_rbExistLogin {
            get {
                return ResourceManager.GetString("FormDbsLogin_rbExistLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anpassad inloggning i databas.
        /// </summary>
        internal static string FormDbsLoginFormDbsLogin {
            get {
                return ResourceManager.GetString("FormDbsLoginFormDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Bakåt.
        /// </summary>
        internal static string FormServerDatabase_bBack {
            get {
                return ResourceManager.GetString("FormServerDatabase_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormServerDatabase_bCancel {
            get {
                return ResourceManager.GetString("FormServerDatabase_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nästa &gt;.
        /// </summary>
        internal static string FormServerDatabase_bNext {
            get {
                return ResourceManager.GetString("FormServerDatabase_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas namn:.
        /// </summary>
        internal static string FormServerDatabase_lDatabaseName {
            get {
                return ResourceManager.GetString("FormServerDatabase_lDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söker efter databaser .....
        /// </summary>
        internal static string FormServerDatabase_lProgress {
            get {
                return ResourceManager.GetString("FormServerDatabase_lProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server:.
        /// </summary>
        internal static string FormServerDatabase_lSqlServer {
            get {
                return ResourceManager.GetString("FormServerDatabase_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen ange databasnamn!.
        /// </summary>
        internal static string FormServerDatabaseEnterDatabaseName {
            get {
                return ResourceManager.GetString("FormServerDatabaseEnterDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen ange databasnamn för separat databas händelselogg!.
        /// </summary>
        internal static string FormServerDatabaseEnterExternalDatabaseName {
            get {
                return ResourceManager.GetString("FormServerDatabaseEnterExternalDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server inställningar.
        /// </summary>
        internal static string FormServerDatabasefServerDatabase {
            get {
                return ResourceManager.GetString("FormServerDatabasefServerDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login för separat händelselogg databas misslyckades. Användare är inte giltlig.
        /// </summary>
        internal static string FormServerExternalDatabaseLoginUserNotValid {
            get {
                return ResourceManager.GetString("FormServerExternalDatabaseLoginUserNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Bakåt.
        /// </summary>
        internal static string FormServerLogin_bBack {
            get {
                return ResourceManager.GetString("FormServerLogin_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormServerLogin_bCancel {
            get {
                return ResourceManager.GetString("FormServerLogin_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nästa &gt;.
        /// </summary>
        internal static string FormServerLogin_bNext {
            get {
                return ResourceManager.GetString("FormServerLogin_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login för Contal Nova Server i databas.
        /// </summary>
        internal static string FormServerLogin_gbLoginForDatabase {
            get {
                return ResourceManager.GetString("FormServerLogin_gbLoginForDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggningsnamn:.
        /// </summary>
        internal static string FormServerLogin_lLoginName {
            get {
                return ResourceManager.GetString("FormServerLogin_lLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inställningar för databasinloggning.
        /// </summary>
        internal static string FormServerLogin_lMainInfo {
            get {
                return ResourceManager.GetString("FormServerLogin_lMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord:.
        /// </summary>
        internal static string FormServerLogin_lPassword {
            get {
                return ResourceManager.GetString("FormServerLogin_lPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server:.
        /// </summary>
        internal static string FormServerLogin_lSqlServer {
            get {
                return ResourceManager.GetString("FormServerLogin_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard databas inloggning för CONTAL NOVA.
        /// </summary>
        internal static string FormServerLogin_rbUseCGPLogin {
            get {
                return ResourceManager.GetString("FormServerLogin_rbUseCGPLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anpassad databas inloggning.
        /// </summary>
        internal static string FormServerLogin_rbUseCustomLogin {
            get {
                return ResourceManager.GetString("FormServerLogin_rbUseCustomLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemadministratörs login (anges ovan).
        /// </summary>
        internal static string FormServerLogin_rbUseSaLogin {
            get {
                return ResourceManager.GetString("FormServerLogin_rbUseSaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server inställningar.
        /// </summary>
        internal static string FormServerLoginfServerLogin {
            get {
                return ResourceManager.GetString("FormServerLoginfServerLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version av Microsoft SQL server stöds ej. Microsoft SQL Server 2008 eller senare krävs..
        /// </summary>
        internal static string FormServerLoginSQLServerVersionNotValid {
            get {
                return ResourceManager.GetString("FormServerLoginSQLServerVersionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användare ej giltlig.
        /// </summary>
        internal static string FormServerLoginUserNotValid {
            get {
                return ResourceManager.GetString("FormServerLoginUserNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormServerSelect_bCancel {
            get {
                return ResourceManager.GetString("FormServerSelect_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nästa &gt;.
        /// </summary>
        internal static string FormServerSelect_bNext {
            get {
                return ResourceManager.GetString("FormServerSelect_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Använd separat databas för händelselogg.
        /// </summary>
        internal static string FormServerSelect_chbEnableExternalDatabase {
            get {
                return ResourceManager.GetString("FormServerSelect_chbEnableExternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj SQL Server.
        /// </summary>
        internal static string FormServerSelect_lMainInfo {
            get {
                return ResourceManager.GetString("FormServerSelect_lMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söker efter SQL Servrar ....
        /// </summary>
        internal static string FormServerSelect_lProgress {
            get {
                return ResourceManager.GetString("FormServerSelect_lProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server för separat databas händelselogg.
        /// </summary>
        internal static string FormServerSelect_lServerForExternalDatabase {
            get {
                return ResourceManager.GetString("FormServerSelect_lServerForExternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server för databas.
        /// </summary>
        internal static string FormServerSelect_lServerInfo {
            get {
                return ResourceManager.GetString("FormServerSelect_lServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server för separat databas händelselogg.
        /// </summary>
        internal static string FormServerSelect_lServerInfoExternalDatabase {
            get {
                return ResourceManager.GetString("FormServerSelect_lServerInfoExternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server inställningar.
        /// </summary>
        internal static string FormServerSelectfServerSelect {
            get {
                return ResourceManager.GetString("FormServerSelectfServerSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen välj SQL Server!.
        /// </summary>
        internal static string FormServerSelectSelectSQLServer {
            get {
                return ResourceManager.GetString("FormServerSelectSelectSQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas ändring lyckades.
        /// </summary>
        internal static string FormUdateDatabaseDatabaseAltered {
            get {
                return ResourceManager.GetString("FormUdateDatabaseDatabaseAltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Bakåt.
        /// </summary>
        internal static string FormUpdateDatabase_bBack {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormUpdateDatabase_bCancel {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändring av DBS.
        /// </summary>
        internal static string FormUpdateDatabase_bFixDbs {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_bFixDbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utför.
        /// </summary>
        internal static string FormUpdateDatabase_bPerform {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_bPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra.
        /// </summary>
        internal static string FormUpdateDatabase_cbAlterLogin {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_cbAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas:.
        /// </summary>
        internal static string FormUpdateDatabase_lDatabase {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_lDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        internal static string FormUpdateDatabase_lLogin {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_lLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pågår:.
        /// </summary>
        internal static string FormUpdateDatabase_lProgress {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_lProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server:.
        /// </summary>
        internal static string FormUpdateDatabase_lSqlServer {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stäng.
        /// </summary>
        internal static string FormUpdateDatabaseClose {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra inloggning krävs!.
        /// </summary>
        internal static string FormUpdateDatabaseErrorAlterLogin {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseErrorAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det uppstod fel vid ändring av databas..
        /// </summary>
        internal static string FormUpdateDatabaseErrorsDatabaseAlter {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseErrorsDatabaseAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login måste ändras..
        /// </summary>
        internal static string FormUpdateDatabaseErrorUserAlter {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseErrorUserAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppdatera databas.
        /// </summary>
        internal static string FormUpdateDatabasefUpdateDatabase {
            get {
                return ResourceManager.GetString("FormUpdateDatabasefUpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknade kolumner.
        /// </summary>
        internal static string FormUpdateDatabaseORMMissColumns {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseORMMissColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL saknar kolumner.
        /// </summary>
        internal static string FormUpdateDatabaseSQLMissColumns {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseSQLMissColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel kolumner, kolumner i systemet stämmer ej med kolumnerna i databasen (det går ej att skapa nya tomma eller unika kolumner).
        /// </summary>
        internal static string FormUpdateDatabaseWrongColumns {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseWrongColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Bakåt.
        /// </summary>
        internal static string FormUserSettings_bBack {
            get {
                return ResourceManager.GetString("FormUserSettings_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormUserSettings_bCancel {
            get {
                return ResourceManager.GetString("FormUserSettings_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nästa &gt;.
        /// </summary>
        internal static string FormUserSettings_bNext {
            get {
                return ResourceManager.GetString("FormUserSettings_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen ange inloggningsnamn..
        /// </summary>
        internal static string FormUserSettingsEnterLoginName {
            get {
                return ResourceManager.GetString("FormUserSettingsEnterLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server inställningar.
        /// </summary>
        internal static string FormUserSettingsfUserSettings {
            get {
                return ResourceManager.GetString("FormUserSettingsfUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggningsnamn:.
        /// </summary>
        internal static string FormUserSettingslabel1 {
            get {
                return ResourceManager.GetString("FormUserSettingslabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inställningar för inloggning.
        /// </summary>
        internal static string FormUserSettingslabel2 {
            get {
                return ResourceManager.GetString("FormUserSettingslabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bläddra.
        /// </summary>
        internal static string General_bBrowse {
            get {
                return ResourceManager.GetString("General_bBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separat databas för händelselogg.
        /// </summary>
        internal static string General_gbExternalDatabase {
            get {
                return ResourceManager.GetString("General_gbExternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huvuddatabas.
        /// </summary>
        internal static string General_gbMainDatabase {
            get {
                return ResourceManager.GetString("General_gbMainDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa nytt lösenord för inloggning.
        /// </summary>
        internal static string GenerateNewPassword {
            get {
                return ResourceManager.GetString("GenerateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databasen innehåller alla ORM tabeller.
        /// </summary>
        internal static string InfoDbsHasAllTable {
            get {
                return ResourceManager.GetString("InfoDbsHasAllTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åtgärda fel stöds ej.
        /// </summary>
        internal static string InfoFixNotSupported {
            get {
                return ResourceManager.GetString("InfoFixNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknade tabeller i databas:.
        /// </summary>
        internal static string InfoMissedTable {
            get {
                return ResourceManager.GetString("InfoMissedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tyvärr finns Ingen Comparer laddad.
        /// </summary>
        internal static string InfoNoComparer {
            get {
                return ResourceManager.GetString("InfoNoComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga fel.
        /// </summary>
        internal static string InfoNoErrors {
            get {
                return ResourceManager.GetString("InfoNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabell:.
        /// </summary>
        internal static string InfoTable {
            get {
                return ResourceManager.GetString("InfoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabeller som inte har alla ORM kolumner i databas:.
        /// </summary>
        internal static string InfoTableMissColumn {
            get {
                return ResourceManager.GetString("InfoTableMissColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabeller med oanvända kolumner i databasen:.
        /// </summary>
        internal static string InfoTableUselessColumn {
            get {
                return ResourceManager.GetString("InfoTableUselessColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabell med felaktiga kolumner i databas:.
        /// </summary>
        internal static string InfoTableWrongColumns {
            get {
                return ResourceManager.GetString("InfoTableWrongColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konvertering krävs, tryck på Utför för att starta konverteringsmodulerna.
        /// </summary>
        internal static string PerformConversion {
            get {
                return ResourceManager.GetString("PerformConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra inloggning:.
        /// </summary>
        internal static string QuestionAlterDbsLogin {
            get {
                return ResourceManager.GetString("QuestionAlterDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login måste ändras:.
        /// </summary>
        internal static string QuestionAlterLogin {
            get {
                return ResourceManager.GetString("QuestionAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . utför processen?.
        /// </summary>
        internal static string QuestionAlterLoginEnd {
            get {
                return ResourceManager.GetString("QuestionAlterLoginEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill Ni göra en backup av databasen?.
        /// </summary>
        internal static string QuestionBackupDatabase {
            get {
                return ResourceManager.GetString("QuestionBackupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup av databas misslyckades. Vill du fortsätta uppdatering av databas?.
        /// </summary>
        internal static string QuestionBackupDatabaseFailedContinueUpdate {
            get {
                return ResourceManager.GetString("QuestionBackupDatabaseFailedContinueUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt konfigurering av databas?.
        /// </summary>
        internal static string QuestionCancelDbConfiguration {
            get {
                return ResourceManager.GetString("QuestionCancelDbConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa inloggning:.
        /// </summary>
        internal static string QuestionCreateDbsLogin {
            get {
                return ResourceManager.GetString("QuestionCreateDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigör händelselog från huvuddatabasen?.
        /// </summary>
        internal static string QuestionDropExternDbs {
            get {
                return ResourceManager.GetString("QuestionDropExternDbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange rättigheter på katalogen för SQL Servern.
        /// </summary>
        internal static string QuestionSetRightsForSQL {
            get {
                return ResourceManager.GetString("QuestionSetRightsForSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppdatering av databas misslyckades. Vill Ni återställa databasen?.
        /// </summary>
        internal static string QuestionUpdateFailedRestoreDatabase {
            get {
                return ResourceManager.GetString("QuestionUpdateFailedRestoreDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal Nova letar efter SQL Servrar.
        /// </summary>
        internal static string searchingForSqlServers {
            get {
                return ResourceManager.GetString("searchingForSqlServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databas backup.
        /// </summary>
        internal static string TextBackupDatabase {
            get {
                return ResourceManager.GetString("TextBackupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup av databas misslyckades.
        /// </summary>
        internal static string TextBackupDatabaseFailed {
            get {
                return ResourceManager.GetString("TextBackupDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup av databas lyckades.
        /// </summary>
        internal static string TextBackupDatabaseSucceeded {
            get {
                return ResourceManager.GetString("TextBackupDatabaseSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns oanvända kolumner i databasen.
        /// </summary>
        internal static string TextInDatabaseAreUselessColumns {
            get {
                return ResourceManager.GetString("TextInDatabaseAreUselessColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anpassad databas inloggning anges i nästa steg.
        /// </summary>
        internal static string TextNotSetLoginName {
            get {
                return ResourceManager.GetString("TextNotSetLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återställ databas.
        /// </summary>
        internal static string TextRestoreDatabase {
            get {
                return ResourceManager.GetString("TextRestoreDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återställning av databas misslyckades.
        /// </summary>
        internal static string TextRestoreDatabaseFailed {
            get {
                return ResourceManager.GetString("TextRestoreDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återställning av databas lyckades.
        /// </summary>
        internal static string TextRestoreDatabaseSucceeded {
            get {
                return ResourceManager.GetString("TextRestoreDatabaseSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starta databas backup.
        /// </summary>
        internal static string TextStartBackupDatabase {
            get {
                return ResourceManager.GetString("TextStartBackupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starta återställning av databas.
        /// </summary>
        internal static string TextStartRestoreDatabase {
            get {
                return ResourceManager.GetString("TextStartRestoreDatabase", resourceCulture);
            }
        }
    }
}
