//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.DBSCreator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Slovak {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Slovak() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.DBSCreator.Localization.Slovak", typeof(Localization_Slovak).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprava tabuľky SystemVersion.
        /// </summary>
        internal static string cgpCorrection1 {
            get {
                return ResourceManager.GetString("cgpCorrection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprava tabuľky SystemVersion zlyhala.
        /// </summary>
        internal static string cgpCorrection1fail {
            get {
                return ResourceManager.GetString("cgpCorrection1fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprava tabuľky SystemVersion vykonaná.
        /// </summary>
        internal static string cgpCorrection1success {
            get {
                return ResourceManager.GetString("cgpCorrection1success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete pokračovať napriek tomu ?.
        /// </summary>
        internal static string cgpCorrectionContinueAnyway {
            get {
                return ResourceManager.GetString("cgpCorrectionContinueAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uistite sa, že má databáza správnu štruktúru.
        /// </summary>
        internal static string cgpCorrectionDatabaseHasCorrectStructure {
            get {
                return ResourceManager.GetString("cgpCorrectionDatabaseHasCorrectStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprava tabuliek pre verziu.
        /// </summary>
        internal static string cgpCorrectionPart {
            get {
                return ResourceManager.GetString("cgpCorrectionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zlyhala.
        /// </summary>
        internal static string cgpCorrectionPartFailed {
            get {
                return ResourceManager.GetString("cgpCorrectionPartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bola vykonaná úspešne.
        /// </summary>
        internal static string cgpCorrectionPartSucceeded {
            get {
                return ResourceManager.GetString("cgpCorrectionPartSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprava tabuliek logovej databázy pre verziu.
        /// </summary>
        internal static string cgpEventlogCorrectionPart {
            get {
                return ResourceManager.GetString("cgpEventlogCorrectionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprava NCAS tabuliek pre verziu.
        /// </summary>
        internal static string cgpNCASCorrectionPart {
            get {
                return ResourceManager.GetString("cgpNCASCorrectionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovať.
        /// </summary>
        internal static string DbsConversion_bContinue {
            get {
                return ResourceManager.GetString("DbsConversion_bContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konverzia databázy.
        /// </summary>
        internal static string DbsConversionDbsConversion {
            get {
                return ResourceManager.GetString("DbsConversionDbsConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušiť.
        /// </summary>
        internal static string DbsLogin_bCancel {
            get {
                return ResourceManager.GetString("DbsLogin_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string DbsLogin_bgDbsLogin {
            get {
                return ResourceManager.GetString("DbsLogin_bgDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DbsLogin_bOk {
            get {
                return ResourceManager.GetString("DbsLogin_bOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno.
        /// </summary>
        internal static string DbsLogin_lName {
            get {
                return ResourceManager.GetString("DbsLogin_lName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string DbsLogin_lPassword {
            get {
                return ResourceManager.GetString("DbsLogin_lPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voliteľný login.
        /// </summary>
        internal static string DbsLogin_rbCustomDbsLogin {
            get {
                return ResourceManager.GetString("DbsLogin_rbCustomDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generovať nový cgpLogin.
        /// </summary>
        internal static string DbsLogin_rbGenrateNewCglLogin {
            get {
                return ResourceManager.GetString("DbsLogin_rbGenrateNewCglLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dbs login.
        /// </summary>
        internal static string DbsLoginDbsLogin {
            get {
                return ResourceManager.GetString("DbsLoginDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava užívateľa zlyhala..
        /// </summary>
        internal static string ErrorAlterLogin {
            get {
                return ResourceManager.GetString("ErrorAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravenie loginu zlyhalo.
        /// </summary>
        internal static string ErrorAlterUserFailed {
            get {
                return ResourceManager.GetString("ErrorAlterUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvorenie loginu zlyhalo.
        /// </summary>
        internal static string ErrorCreateUserFailed {
            get {
                return ResourceManager.GetString("ErrorCreateUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza už existuje.
        /// </summary>
        internal static string ErrorDatabaseAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorDatabaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedá sa vytvoriť adresár pre databázy.
        /// </summary>
        internal static string ErrorDirectoryCreationFailed {
            get {
                return ResourceManager.GetString("ErrorDirectoryCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadajte prihlasovacie meno.
        /// </summary>
        internal static string ErrorEntryLogin {
            get {
                return ResourceManager.GetString("ErrorEntryLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadajte heslo.
        /// </summary>
        internal static string ErrorEntryPassword {
            get {
                return ResourceManager.GetString("ErrorEntryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba extrená databáza musí byť iná ako hlavná databáza.
        /// </summary>
        internal static string ErrorExternDbsNameEqualToMainDbs {
            get {
                return ResourceManager.GetString("ErrorExternDbsNameEqualToMainDbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlyhalo generovanie nového loginu.
        /// </summary>
        internal static string ErrorFailedGenerateLogin {
            get {
                return ResourceManager.GetString("ErrorFailedGenerateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno nie je povolené.
        /// </summary>
        internal static string ErrorNameNotAllowed {
            get {
                return ResourceManager.GetString("ErrorNameNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skončiť.
        /// </summary>
        internal static string FormAlterTables_bCancel {
            get {
                return ResourceManager.GetString("FormAlterTables_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobraz.
        /// </summary>
        internal static string FormAlterTables_bListErrors {
            get {
                return ResourceManager.GetString("FormAlterTables_bListErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opraviť.
        /// </summary>
        internal static string FormAlterTables_bRunAlter {
            get {
                return ResourceManager.GetString("FormAlterTables_bRunAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza obsahuje sĺpce, ktoré nie sú v hbm schéme, Úprava tabuľky ich odstráni..
        /// </summary>
        internal static string FormAlterTables_eAlterInfo {
            get {
                return ResourceManager.GetString("FormAlterTables_eAlterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pri alterácii databázy..
        /// </summary>
        internal static string FormAlterTablesAlterDatabaseFailed {
            get {
                return ResourceManager.GetString("FormAlterTablesAlterDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterácia databázy je ukončená..
        /// </summary>
        internal static string FormAlterTablesAlterDatabaseFinished {
            get {
                return ResourceManager.GetString("FormAlterTablesAlterDatabaseFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stĺpec.
        /// </summary>
        internal static string FormAlterTablesColumn {
            get {
                return ResourceManager.GetString("FormAlterTablesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza obsahuje chyby..
        /// </summary>
        internal static string FormAlterTablesDatabaseConstainErrors {
            get {
                return ResourceManager.GetString("FormAlterTablesDatabaseConstainErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza je OK..
        /// </summary>
        internal static string FormAlterTablesDatabaseOK {
            get {
                return ResourceManager.GetString("FormAlterTablesDatabaseOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravenie tabuliek databázy.
        /// </summary>
        internal static string FormAlterTablesfAlterTables {
            get {
                return ResourceManager.GetString("FormAlterTablesfAlterTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuľka.
        /// </summary>
        internal static string FormAlterTablesTable {
            get {
                return ResourceManager.GetString("FormAlterTablesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Späť.
        /// </summary>
        internal static string FormBeforeExecution_bBack {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skončiť.
        /// </summary>
        internal static string FormBeforeExecution_bCancel {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vykonať.
        /// </summary>
        internal static string FormBeforeExecution_bPerform {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Späť.
        /// </summary>
        internal static string FormBeforeExecution_bUndoDatabase {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bUndoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Späť.
        /// </summary>
        internal static string FormBeforeExecution_bUndoUser {
            get {
                return ResourceManager.GetString("FormBeforeExecution_bUndoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepísať existujúcu.
        /// </summary>
        internal static string FormBeforeExecution_cbAlterLogin {
            get {
                return ResourceManager.GetString("FormBeforeExecution_cbAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza:.
        /// </summary>
        internal static string FormBeforeExecution_lDatabase {
            get {
                return ResourceManager.GetString("FormBeforeExecution_lDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlasovacie meno:.
        /// </summary>
        internal static string FormBeforeExecution_lLogin {
            get {
                return ResourceManager.GetString("FormBeforeExecution_lLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav:.
        /// </summary>
        internal static string FormBeforeExecution_lProgress {
            get {
                return ResourceManager.GetString("FormBeforeExecution_lProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server:.
        /// </summary>
        internal static string FormBeforeExecution_lSqlServer {
            get {
                return ResourceManager.GetString("FormBeforeExecution_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pri vytváraní tabuliek..
        /// </summary>
        internal static string FormBeforeExecutionCreationTablesFail {
            get {
                return ResourceManager.GetString("FormBeforeExecutionCreationTablesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pre vytváraní užívateľa..
        /// </summary>
        internal static string FormBeforeExecutionCreationUserFail {
            get {
                return ResourceManager.GetString("FormBeforeExecutionCreationUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza zrušená..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseCancelled {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza nemôže byť vytvorená..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseCannotByCreated {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseCannotByCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza vytvorená..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseCreated {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pri vytváraní databázy..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseCreationFailed {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza už existuje..
        /// </summary>
        internal static string FormBeforeExecutionDatabaseExists {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDatabaseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pri rušení databázy..
        /// </summary>
        internal static string FormBeforeExecutionDropDatabaseFail {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDropDatabaseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pri rušení užívateľa..
        /// </summary>
        internal static string FormBeforeExecutionDropUserFail {
            get {
                return ResourceManager.GetString("FormBeforeExecutionDropUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvorenie databázy.
        /// </summary>
        internal static string FormBeforeExecutionfBeforeExecution {
            get {
                return ResourceManager.GetString("FormBeforeExecutionfBeforeExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotovo.
        /// </summary>
        internal static string FormBeforeExecutionFinished {
            get {
                return ResourceManager.GetString("FormBeforeExecutionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušiť užívateľa.
        /// </summary>
        internal static string FormBeforeExecutionQuestionDeleteUser {
            get {
                return ResourceManager.GetString("FormBeforeExecutionQuestionDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušiť databázu.
        /// </summary>
        internal static string FormBeforeExecutionQuestionDropDatabase {
            get {
                return ResourceManager.GetString("FormBeforeExecutionQuestionDropDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuľky vytvorené..
        /// </summary>
        internal static string FormBeforeExecutionTablesCreated {
            get {
                return ResourceManager.GetString("FormBeforeExecutionTablesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užívateľ zrušený..
        /// </summary>
        internal static string FormBeforeExecutionUserCancelled {
            get {
                return ResourceManager.GetString("FormBeforeExecutionUserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užívateľ vytvorený..
        /// </summary>
        internal static string FormBeforeExecutionUserCreated {
            get {
                return ResourceManager.GetString("FormBeforeExecutionUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užívateľ už existuje..
        /// </summary>
        internal static string FormBeforeExecutionUserExists {
            get {
                return ResourceManager.GetString("FormBeforeExecutionUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Späť.
        /// </summary>
        internal static string FormConfirmation_bBack {
            get {
                return ResourceManager.GetString("FormConfirmation_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skončiť.
        /// </summary>
        internal static string FormConfirmation_bCancel {
            get {
                return ResourceManager.GetString("FormConfirmation_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotovo.
        /// </summary>
        internal static string FormConfirmation_bNext {
            get {
                return ResourceManager.GetString("FormConfirmation_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre SQL server.
        /// </summary>
        internal static string FormConfirmationfConfirmation {
            get {
                return ResourceManager.GetString("FormConfirmationfConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre SQL server sú hotové..
        /// </summary>
        internal static string FormConfirmationlabel1 {
            get {
                return ResourceManager.GetString("FormConfirmationlabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stačte Hotovo pre vytvorenie databázy..
        /// </summary>
        internal static string FormConfirmationlabel2 {
            get {
                return ResourceManager.GetString("FormConfirmationlabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Späť.
        /// </summary>
        internal static string FormDatabaseSettings_bBack {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skončiť.
        /// </summary>
        internal static string FormDatabaseSettings_bCancel {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ďalej &gt;.
        /// </summary>
        internal static string FormDatabaseSettings_bNext {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov databázy:.
        /// </summary>
        internal static string FormDatabaseSettings_lDatabaseName {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_lDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre databázu.
        /// </summary>
        internal static string FormDatabaseSettings_lMainInfo {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_lMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesta k súborom databázy.
        /// </summary>
        internal static string FormDatabaseSettings_lPath {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_lPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server:.
        /// </summary>
        internal static string FormDatabaseSettings_lSqlServer {
            get {
                return ResourceManager.GetString("FormDatabaseSettings_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre SQL server.
        /// </summary>
        internal static string FormDatabaseSettingsfDatabaseSettings {
            get {
                return ResourceManager.GetString("FormDatabaseSettingsfDatabaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Späť.
        /// </summary>
        internal static string FormServerDatabase_bBack {
            get {
                return ResourceManager.GetString("FormServerDatabase_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skončiť.
        /// </summary>
        internal static string FormServerDatabase_bCancel {
            get {
                return ResourceManager.GetString("FormServerDatabase_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ďalej &gt;.
        /// </summary>
        internal static string FormServerDatabase_bNext {
            get {
                return ResourceManager.GetString("FormServerDatabase_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno databázy:.
        /// </summary>
        internal static string FormServerDatabase_lDatabaseName {
            get {
                return ResourceManager.GetString("FormServerDatabase_lDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vyhľadávam databázy ....
        /// </summary>
        internal static string FormServerDatabase_lProgress {
            get {
                return ResourceManager.GetString("FormServerDatabase_lProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server:.
        /// </summary>
        internal static string FormServerDatabase_lSqlServer {
            get {
                return ResourceManager.GetString("FormServerDatabase_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím zadajte meno databázy!.
        /// </summary>
        internal static string FormServerDatabaseEnterDatabaseName {
            get {
                return ResourceManager.GetString("FormServerDatabaseEnterDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím zadajte meno databázy pre separovanú databázu pre logy udalostí!.
        /// </summary>
        internal static string FormServerDatabaseEnterExternalDatabaseName {
            get {
                return ResourceManager.GetString("FormServerDatabaseEnterExternalDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre SQL server.
        /// </summary>
        internal static string FormServerDatabasefServerDatabase {
            get {
                return ResourceManager.GetString("FormServerDatabasefServerDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlásenie na server pre separovanú databázu pre logy udalostí zlyhalo. Užívateľ nie je platný.
        /// </summary>
        internal static string FormServerExternalDatabaseLoginUserNotValid {
            get {
                return ResourceManager.GetString("FormServerExternalDatabaseLoginUserNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Späť.
        /// </summary>
        internal static string FormServerLogin_bBack {
            get {
                return ResourceManager.GetString("FormServerLogin_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skončiť.
        /// </summary>
        internal static string FormServerLogin_bCancel {
            get {
                return ResourceManager.GetString("FormServerLogin_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ďalej &gt;.
        /// </summary>
        internal static string FormServerLogin_bNext {
            get {
                return ResourceManager.GetString("FormServerLogin_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlasovacie meno:.
        /// </summary>
        internal static string FormServerLogin_lLoginName {
            get {
                return ResourceManager.GetString("FormServerLogin_lLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre prihlásenie sa do databázy.
        /// </summary>
        internal static string FormServerLogin_lMainInfo {
            get {
                return ResourceManager.GetString("FormServerLogin_lMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo:.
        /// </summary>
        internal static string FormServerLogin_lPassword {
            get {
                return ResourceManager.GetString("FormServerLogin_lPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server:.
        /// </summary>
        internal static string FormServerLogin_lSqlServer {
            get {
                return ResourceManager.GetString("FormServerLogin_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre SQL server.
        /// </summary>
        internal static string FormServerLoginfServerLogin {
            get {
                return ResourceManager.GetString("FormServerLoginfServerLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chybný užívateľ..
        /// </summary>
        internal static string FormServerLoginUserNotValid {
            get {
                return ResourceManager.GetString("FormServerLoginUserNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skončiť.
        /// </summary>
        internal static string FormServerSelect_bCancel {
            get {
                return ResourceManager.GetString("FormServerSelect_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ďalej &gt;.
        /// </summary>
        internal static string FormServerSelect_bNext {
            get {
                return ResourceManager.GetString("FormServerSelect_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povoliť separovanú databázu pre logy udalostí.
        /// </summary>
        internal static string FormServerSelect_chbEnableExternalDatabase {
            get {
                return ResourceManager.GetString("FormServerSelect_chbEnableExternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte SQL server.
        /// </summary>
        internal static string FormServerSelect_lMainInfo {
            get {
                return ResourceManager.GetString("FormServerSelect_lMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhľadám SQL servery ....
        /// </summary>
        internal static string FormServerSelect_lProgress {
            get {
                return ResourceManager.GetString("FormServerSelect_lProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server pre separovanú databázu pre logy udalostí.
        /// </summary>
        internal static string FormServerSelect_lServerForExternalDatabase {
            get {
                return ResourceManager.GetString("FormServerSelect_lServerForExternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server pre databázu.
        /// </summary>
        internal static string FormServerSelect_lServerInfo {
            get {
                return ResourceManager.GetString("FormServerSelect_lServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server pre separovanú databázu pre logy udalostí.
        /// </summary>
        internal static string FormServerSelect_lServerInfoExternalDatabase {
            get {
                return ResourceManager.GetString("FormServerSelect_lServerInfoExternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre SQL server.
        /// </summary>
        internal static string FormServerSelectfServerSelect {
            get {
                return ResourceManager.GetString("FormServerSelectfServerSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyberte SQL server!.
        /// </summary>
        internal static string FormServerSelectSelectSQLServer {
            get {
                return ResourceManager.GetString("FormServerSelectSelectSQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza bola úspešne altrovaná..
        /// </summary>
        internal static string FormUdateDatabaseDatabaseAltered {
            get {
                return ResourceManager.GetString("FormUdateDatabaseDatabaseAltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Späť.
        /// </summary>
        internal static string FormUpdateDatabase_bBack {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skončiť.
        /// </summary>
        internal static string FormUpdateDatabase_bCancel {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraviť DBS.
        /// </summary>
        internal static string FormUpdateDatabase_bFixDbs {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_bFixDbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vykonať.
        /// </summary>
        internal static string FormUpdateDatabase_bPerform {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_bPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraviť.
        /// </summary>
        internal static string FormUpdateDatabase_cbAlterLogin {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_cbAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza:.
        /// </summary>
        internal static string FormUpdateDatabase_lDatabase {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_lDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlasovacie meno:.
        /// </summary>
        internal static string FormUpdateDatabase_lLogin {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_lLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav:.
        /// </summary>
        internal static string FormUpdateDatabase_lProgress {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_lProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server:.
        /// </summary>
        internal static string FormUpdateDatabase_lSqlServer {
            get {
                return ResourceManager.GetString("FormUpdateDatabase_lSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavri.
        /// </summary>
        internal static string FormUpdateDatabaseClose {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava loginu je nutná!.
        /// </summary>
        internal static string FormUpdateDatabaseErrorAlterLogin {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseErrorAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskytli sa chyby pri altrovaní databázy..
        /// </summary>
        internal static string FormUpdateDatabaseErrorsDatabaseAlter {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseErrorsDatabaseAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login je potrebné upraviť.
        /// </summary>
        internal static string FormUpdateDatabaseErrorUserAlter {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseErrorUserAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravenie schémy databázy.
        /// </summary>
        internal static string FormUpdateDatabasefUpdateDatabase {
            get {
                return ResourceManager.GetString("FormUpdateDatabasefUpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chýbajúce stĺpce v Orm.
        /// </summary>
        internal static string FormUpdateDatabaseORMMissColumns {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseORMMissColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chýbajúce stĺpce v SQL databáze.
        /// </summary>
        internal static string FormUpdateDatabaseSQLMissColumns {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseSQLMissColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chybné stĺpce, stĺpce v schéme nezodpovedajú stĺpcom v databáze (nemôže vytvoriť nový NOT NULL alebo UNIQUE stĺpec).
        /// </summary>
        internal static string FormUpdateDatabaseWrongColumns {
            get {
                return ResourceManager.GetString("FormUpdateDatabaseWrongColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Späť.
        /// </summary>
        internal static string FormUserSettings_bBack {
            get {
                return ResourceManager.GetString("FormUserSettings_bBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skončiť.
        /// </summary>
        internal static string FormUserSettings_bCancel {
            get {
                return ResourceManager.GetString("FormUserSettings_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ďalej &gt;.
        /// </summary>
        internal static string FormUserSettings_bNext {
            get {
                return ResourceManager.GetString("FormUserSettings_bNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím zadajte prihlasovacie meno..
        /// </summary>
        internal static string FormUserSettingsEnterLoginName {
            get {
                return ResourceManager.GetString("FormUserSettingsEnterLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre SQL server.
        /// </summary>
        internal static string FormUserSettingsfUserSettings {
            get {
                return ResourceManager.GetString("FormUserSettingsfUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlasovacie meno:.
        /// </summary>
        internal static string FormUserSettingslabel1 {
            get {
                return ResourceManager.GetString("FormUserSettingslabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia pre prihlásenie.
        /// </summary>
        internal static string FormUserSettingslabel2 {
            get {
                return ResourceManager.GetString("FormUserSettingslabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezerať.
        /// </summary>
        internal static string General_bBrowse {
            get {
                return ResourceManager.GetString("General_bBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separovaná databáza pre logy udalostí.
        /// </summary>
        internal static string General_gbExternalDatabase {
            get {
                return ResourceManager.GetString("General_gbExternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavná databáza.
        /// </summary>
        internal static string General_gbMainDatabase {
            get {
                return ResourceManager.GetString("General_gbMainDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vygenerovať nové heslo pre login.
        /// </summary>
        internal static string GenerateNewPassword {
            get {
                return ResourceManager.GetString("GenerateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáza obsahuje všetky ORM tabuľky..
        /// </summary>
        internal static string InfoDbsHasAllTable {
            get {
                return ResourceManager.GetString("InfoDbsHasAllTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprava nie je podporovaná..
        /// </summary>
        internal static string InfoFixNotSupported {
            get {
                return ResourceManager.GetString("InfoFixNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chýbajúce tabuľky v databáze:.
        /// </summary>
        internal static string InfoMissedTable {
            get {
                return ResourceManager.GetString("InfoMissedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer nenačítaný.
        /// </summary>
        internal static string InfoNoComparer {
            get {
                return ResourceManager.GetString("InfoNoComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to žiadne chyby.
        /// </summary>
        internal static string InfoNoErrors {
            get {
                return ResourceManager.GetString("InfoNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuľka: .
        /// </summary>
        internal static string InfoTable {
            get {
                return ResourceManager.GetString("InfoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuľky s chýbajúcimi stĺpcami:.
        /// </summary>
        internal static string InfoTableMissColumn {
            get {
                return ResourceManager.GetString("InfoTableMissColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuľky so zbytočnými stĺpcami:.
        /// </summary>
        internal static string InfoTableUselessColumn {
            get {
                return ResourceManager.GetString("InfoTableUselessColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuľky s nesprávnymi stĺpcami:.
        /// </summary>
        internal static string InfoTableWrongColumns {
            get {
                return ResourceManager.GetString("InfoTableWrongColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konverzia databázy je potrebná, stlačte Vykonať pre zavolanie konverzie.
        /// </summary>
        internal static string PerformConversion {
            get {
                return ResourceManager.GetString("PerformConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraviť login: .
        /// </summary>
        internal static string QuestionAlterDbsLogin {
            get {
                return ResourceManager.GetString("QuestionAlterDbsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je potrebné upraviť login:.
        /// </summary>
        internal static string QuestionAlterLogin {
            get {
                return ResourceManager.GetString("QuestionAlterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , vykonať operáciu?.
        /// </summary>
        internal static string QuestionAlterLoginEnd {
            get {
                return ResourceManager.GetString("QuestionAlterLoginEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastaviť process databázovej konfigurácie?.
        /// </summary>
        internal static string QuestionCancelDbConfiguration {
            get {
                return ResourceManager.GetString("QuestionCancelDbConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmazať tabuľky eventlogov z konfiguračnej databázy?.
        /// </summary>
        internal static string QuestionDropExternDbs {
            get {
                return ResourceManager.GetString("QuestionDropExternDbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastaviť práva nad adresárom pre SQL Server.
        /// </summary>
        internal static string QuestionSetRightsForSQL {
            get {
                return ResourceManager.GetString("QuestionSetRightsForSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systém hľadá dostupné SQL servery.
        /// </summary>
        internal static string searchingForSqlServers {
            get {
                return ResourceManager.GetString("searchingForSqlServers", resourceCulture);
            }
        }
    }
}
