using Contal.Drivers.CardReader;

namespace Contal.Cgp.NCAS.CCU.CardReaderMechanism
{
    public enum CrIconSymbol : ushort
    {
        UnsetLarge = 0x06,
        AlarmAreaIsSet = 0x26,
        SetAlarmArea = 0x26,
        Waiting = 0x27,
        AlarmAreaInSabotage = 0x27,
        SensorsInSabotage = 0x27,
        TimeBuyingExpired = 0x27,
        UnsetAlarmArea = 0x28,
        AlarmAreaIsUnset = 0x28,
        PinRequired = 0x30,
        UnblockSensor = 0x37,
        ActionFailed = 0x37,
        Accepted = 0x39,
        AcknowledgeAlarmArea = 0x39,
        AcknowledgeSensorAlarm = 0x39,
        NotAcknowledged = 0x3D,
        AcknowledgeAll = 0x41,
        AlarmAreasNotAcknowledged = 0x43,
        AlarmAreaIsNotAcknowledged = 0x43,
        AlarmAreas = 0x44,
        SensorsInAlarmNotAcknowledged = 0x45,
        SensorsPermanentlyBlocked = 0x47,
        PermanentlyBlockSensorAlarm = 0x47,
        SensorsTemporarilyBlocked = 0x49,
        TemporarilyBlockSensorAlarm = 0x49,
        TimeBuying = 0x4B,
        TimeBuyingLarge = 0x4C,
        AlarmAreaIsInAlarm = 0x4D,
        AlarmAreasInAlarm = 0x4D,
        ShowAllEventLogs = 0x4F,
        EventLogSmall = 0x4F,
        EventLog = 0x50,
        SensorsNormalNotAcknowledged = 0x51,
        ShowSensors = 0x53,
        Sensors = 0x54,
        SensorsInAlarm = 0x55,
        SensorsNormal = 0x57,
        SetAll = 0x59,
        UnsetAll = 0x5B,
        AlarmAreaIsNormal = 0x5D,
        EmergencyCode = 0x5E,
        NoSymbol = CRMenuCommands.GraphicalMenuNoSymbol,
    }
}