//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.NCAS.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.NCAS.Server.Localization.English", typeof(Localization_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCU has outdated firmware.
        /// </summary>
        public static string CCUOutdatedFirmware {
            get {
                return ResourceManager.GetString("CCUOutdatedFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access system plugin.
        /// </summary>
        public static string CgpNCASServerplugin {
            get {
                return ResourceManager.GetString("CgpNCASServerplugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCU has outdated firmware.
        /// </summary>
        public static string DCUOutdatedFirmware {
            get {
                return ResourceManager.GetString("DCUOutdatedFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of door environments.
        /// </summary>
        public static string DoorEnvironmentCount {
            get {
                return ResourceManager.GetString("DoorEnvironmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCU was unconfigured because of insuffucuent CCU Combo licence count.
        /// </summary>
        public static string InsufficientCCUComboLicenceCount {
            get {
                return ResourceManager.GetString("InsufficientCCUComboLicenceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal supported FW version.
        /// </summary>
        public static string MinimalSupportedFW {
            get {
                return ResourceManager.GetString("MinimalSupportedFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm transmitter.
        /// </summary>
        public static string TextAlarmTransmitter {
            get {
                return ResourceManager.GetString("TextAlarmTransmitter", resourceCulture);
            }
        }
    }
}
