//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.Server.Localization.English", typeof(Localization_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Control List.
        /// </summary>
        internal static string AccessControlLists {
            get {
                return ResourceManager.GetString("AccessControlLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Readers.
        /// </summary>
        internal static string CardReaders {
            get {
                return ResourceManager.GetString("CardReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable CIS integration.
        /// </summary>
        internal static string CISIntegration {
            get {
                return ResourceManager.GetString("CISIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string ColumnAccessDenied {
            get {
                return ResourceManager.GetString("ColumnAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string ColumnBD {
            get {
                return ResourceManager.GetString("ColumnBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full number.
        /// </summary>
        internal static string ColumnCardFullNumber {
            get {
                return ResourceManager.GetString("ColumnCardFullNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder.
        /// </summary>
        internal static string ColumnCardHolder {
            get {
                return ResourceManager.GetString("ColumnCardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        internal static string ColumnCardNumber {
            get {
                return ResourceManager.GetString("ColumnCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Reader.
        /// </summary>
        internal static string ColumnCardReader {
            get {
                return ResourceManager.GetString("ColumnCardReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string ColumnDateFrom {
            get {
                return ResourceManager.GetString("ColumnDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door Ajar Alarm Created.
        /// </summary>
        internal static string ColumnDateTimeCreated {
            get {
                return ResourceManager.GetString("ColumnDateTimeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string ColumnDateTo {
            get {
                return ResourceManager.GetString("ColumnDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string ColumnDepartment {
            get {
                return ResourceManager.GetString("ColumnDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColumnDescription {
            get {
                return ResourceManager.GetString("ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm duration (sec).
        /// </summary>
        internal static string ColumnDuration {
            get {
                return ResourceManager.GetString("ColumnDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ColumnEmail {
            get {
                return ResourceManager.GetString("ColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Beginning Date.
        /// </summary>
        internal static string ColumnEmploymentBeginningDate {
            get {
                return ResourceManager.GetString("ColumnEmploymentBeginningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment End Date.
        /// </summary>
        internal static string ColumnEmploymentEndDate {
            get {
                return ResourceManager.GetString("ColumnEmploymentEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of 1st event.
        /// </summary>
        internal static string ColumnEventlogDateTimeFirst {
            get {
                return ResourceManager.GetString("ColumnEventlogDateTimeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of last event.
        /// </summary>
        internal static string ColumnEventlogDateTimeLast {
            get {
                return ResourceManager.GetString("ColumnEventlogDateTimeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCU name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCU name.
        /// </summary>
        internal static string ColumnParent {
            get {
                return ResourceManager.GetString("ColumnParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string ColumnPerson {
            get {
                return ResourceManager.GetString("ColumnPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID.
        /// </summary>
        internal static string ColumnPersonID {
            get {
                return ResourceManager.GetString("ColumnPersonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string ColumnState {
            get {
                return ResourceManager.GetString("ColumnState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string ColumnTelephone {
            get {
                return ResourceManager.GetString("ColumnTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of connected clients.
        /// </summary>
        internal static string ConnectionCount {
            get {
                return ResourceManager.GetString("ConnectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCU.
        /// </summary>
        internal static string DCUText {
            get {
                return ResourceManager.GetString("DCUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door environment DCU.
        /// </summary>
        internal static string DoorEnvironmentForDCUName {
            get {
                return ResourceManager.GetString("DoorEnvironmentForDCUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door environment.
        /// </summary>
        internal static string DoorEnvironmentName {
            get {
                return ResourceManager.GetString("DoorEnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be empty.
        /// </summary>
        internal static string ErrorEmptyValue {
            get {
                return ResourceManager.GetString("ErrorEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string to the database is not valid.
        /// </summary>
        internal static string ErrorNotValidConnectionString {
            get {
                return ResourceManager.GetString("ErrorNotValidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating a request.
        /// </summary>
        internal static string ErrorOnCreateRequest {
            get {
                return ResourceManager.GetString("ErrorOnCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating a request (could not get CIID).
        /// </summary>
        internal static string ErrorOnCreateRequestCIID {
            get {
                return ResourceManager.GetString("ErrorOnCreateRequestCIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence property set failed (check descriptive set file).
        /// </summary>
        internal static string ErrorOnLicenceProperty {
            get {
                return ResourceManager.GetString("ErrorOnLicenceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load required licence information (certificate, properties).
        ///(*.crt and *.ldsc file must be present).
        /// </summary>
        internal static string ErrorReadLicencePublisherAndProperties {
            get {
                return ResourceManager.GetString("ErrorReadLicencePublisherAndProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FormLicenceRequest_buttonCancel {
            get {
                return ResourceManager.GetString("FormLicenceRequest_buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FormLicenceRequest_buttonSave {
            get {
                return ResourceManager.GetString("FormLicenceRequest_buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer info.
        /// </summary>
        internal static string FormLicenceRequest_groupBoxCustomerInfo {
            get {
                return ResourceManager.GetString("FormLicenceRequest_groupBoxCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact email.
        /// </summary>
        internal static string FormLicenceRequest_labelContactEmail {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact first name.
        /// </summary>
        internal static string FormLicenceRequest_labelContactFirstName {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact last name.
        /// </summary>
        internal static string FormLicenceRequest_labelContactLastName {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact phone.
        /// </summary>
        internal static string FormLicenceRequest_labelContactPhone {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer address.
        /// </summary>
        internal static string FormLicenceRequest_labelCustAddr {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelCustAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        internal static string FormLicenceRequest_labelCustName {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelCustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence request.
        /// </summary>
        internal static string FormLicenceRequestFormLicenceRequest {
            get {
                return ResourceManager.GetString("FormLicenceRequestFormLicenceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string General_Enable {
            get {
                return ResourceManager.GetString("General_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string GeneralOptionsForm_bClose {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string GeneralOptionsForm_bRefreshLicenceList {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bRefreshLicenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string GeneralOptionsForm_bSave {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string GeneralOptionsForm_bSet {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES Remoting.
        /// </summary>
        internal static string GeneralOptionsForm_cbAESEnabled {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_cbAESEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip database reconfiguration.
        /// </summary>
        internal static string GeneralOptionsForm_chbSaveAndSkipDB {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_chbSaveAndSkipDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence file.
        /// </summary>
        internal static string GeneralOptionsForm_labelLicenceFilePath {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_labelLicenceFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aes encryption key.
        /// </summary>
        internal static string GeneralOptionsForm_lAesEncryptionKey {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lAesEncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP port for CNMP loockup.
        /// </summary>
        internal static string GeneralOptionsForm_lCnmpUdpPort {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lCnmpUdpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server firendly name.
        /// </summary>
        internal static string GeneralOptionsForm_lFriendlyName {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind to specific IP address.
        /// </summary>
        internal static string GeneralOptionsForm_lRemotingIpAddress {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lRemotingIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting server port.
        /// </summary>
        internal static string GeneralOptionsForm_lServerPort {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal Nova Server : General options for server.
        /// </summary>
        internal static string GeneralOptionsFormGeneralOptionsForm {
            get {
                return ResourceManager.GetString("GeneralOptionsFormGeneralOptionsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This options is intended mainly for licensing changes
        ///    
        ///Do you really want to skip the database reconfiguration ?.
        /// </summary>
        internal static string GeneralOptionsFormReallySkipDB {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReallySkipDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, reenter the IP address.
        /// </summary>
        internal static string GeneralOptionsFormReenterIpAddress {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReenterIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, reenter remoting server port.
        /// </summary>
        internal static string GeneralOptionsFormReenterRemotingServerPort {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReenterRemotingServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, reenter UDP port for CNMP loockup.
        /// </summary>
        internal static string GeneralOptionsFormReenterUdpPortForCNMP {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReenterUdpPortForCNMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address is not valid.
        /// </summary>
        internal static string GeneralOptionsFormServerIpAddressIsNotValid {
            get {
                return ResourceManager.GetString("GeneralOptionsFormServerIpAddressIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access registry !
        ///    
        ///Please verify, that you&apos;re running configuration mode as administrator.
        /// </summary>
        internal static string GeneralOptionsFormServerNoRegistryWriteAccess {
            get {
                return ResourceManager.GetString("GeneralOptionsFormServerNoRegistryWriteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port is not free.
        /// </summary>
        internal static string GeneralOptionsFormTcpPortIsNotFree {
            get {
                return ResourceManager.GetString("GeneralOptionsFormTcpPortIsNotFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP port is not free.
        /// </summary>
        internal static string GeneralOptionsFormUdpPortIsNotFree {
            get {
                return ResourceManager.GetString("GeneralOptionsFormUdpPortIsNotFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General options are not yet configured !
        ///
        ///Do you really want to close the dialog ?.
        /// </summary>
        internal static string GeneralOptionsFormUnconfiguredReallyContinue {
            get {
                return ResourceManager.GetString("GeneralOptionsFormUnconfiguredReallyContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested type is.
        /// </summary>
        internal static string GeneralRequestedType {
            get {
                return ResourceManager.GetString("GeneralRequestedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID management/Batch design.
        /// </summary>
        internal static string IdManagement {
            get {
                return ResourceManager.GetString("IdManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved license file does not exist or is not in server directory.
        /// </summary>
        internal static string LicenseFileNotInServerDir {
            get {
                return ResourceManager.GetString("LicenseFileNotInServerDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved lincense file has incorrect extension.
        /// </summary>
        internal static string LicenseFileWrongExtension {
            get {
                return ResourceManager.GetString("LicenseFileWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server major version.
        /// </summary>
        internal static string MajorVersion {
            get {
                return ResourceManager.GetString("MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable access plugin.
        /// </summary>
        internal static string NCASPluginEnabled {
            get {
                return ResourceManager.GetString("NCASPluginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expiration.
        /// </summary>
        internal static string NoExpiration {
            get {
                return ResourceManager.GetString("NoExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specified.
        /// </summary>
        internal static string NoSpecified {
            get {
                return ResourceManager.GetString("NoSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable import from CSV/TSV.
        /// </summary>
        internal static string OfflineImport {
            get {
                return ResourceManager.GetString("OfflineImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string OutputText {
            get {
                return ResourceManager.GetString("OutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal nova server is already running. Close the contal nova server?.
        /// </summary>
        internal static string QuestionCloseServer {
            get {
                return ResourceManager.GetString("QuestionCloseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal nova server is already running. Stop service for the contal nova server?.
        /// </summary>
        internal static string QuestionStopService {
            get {
                return ResourceManager.GetString("QuestionStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was successfully created.
        /// </summary>
        internal static string RequestSuccessfullyCreated {
            get {
                return ResourceManager.GetString("RequestSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string SelectStructuredSubSiteForm_RootNode {
            get {
                return ResourceManager.GetString("SelectStructuredSubSiteForm_RootNode", resourceCulture);
            }
        }
    }
}
