//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Slovak {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Slovak() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.Server.Localization.Slovak", typeof(Localization_Slovak).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam prístupových práv.
        /// </summary>
        internal static string AccessControlLists {
            get {
                return ResourceManager.GetString("AccessControlLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snímače kariet.
        /// </summary>
        internal static string CardReaders {
            get {
                return ResourceManager.GetString("CardReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karty.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolenie CIS integrácie.
        /// </summary>
        internal static string CISIntegration {
            get {
                return ResourceManager.GetString("CISIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet odmietnutých prístupov.
        /// </summary>
        internal static string ColumnAccessDenied {
            get {
                return ResourceManager.GetString("ColumnAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum narodenia.
        /// </summary>
        internal static string ColumnBD {
            get {
                return ResourceManager.GetString("ColumnBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celé číslo karty.
        /// </summary>
        internal static string ColumnCardFullNumber {
            get {
                return ResourceManager.GetString("ColumnCardFullNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživateľ.
        /// </summary>
        internal static string ColumnCardHolder {
            get {
                return ResourceManager.GetString("ColumnCardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo karty.
        /// </summary>
        internal static string ColumnCardNumber {
            get {
                return ResourceManager.GetString("ColumnCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snímač.
        /// </summary>
        internal static string ColumnCardReader {
            get {
                return ResourceManager.GetString("ColumnCardReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        internal static string ColumnDateFrom {
            get {
                return ResourceManager.GetString("ColumnDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum vytvorenia alarmu Door Ajar.
        /// </summary>
        internal static string ColumnDateTimeCreated {
            get {
                return ResourceManager.GetString("ColumnDateTimeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string ColumnDateTo {
            get {
                return ResourceManager.GetString("ColumnDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddelenie.
        /// </summary>
        internal static string ColumnDepartment {
            get {
                return ResourceManager.GetString("ColumnDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        internal static string ColumnDescription {
            get {
                return ResourceManager.GetString("ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trvanie alarmu (s).
        /// </summary>
        internal static string ColumnDuration {
            get {
                return ResourceManager.GetString("ColumnDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ColumnEmail {
            get {
                return ResourceManager.GetString("ColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum nástupu do zamestnania.
        /// </summary>
        internal static string ColumnEmploymentBeginningDate {
            get {
                return ResourceManager.GetString("ColumnEmploymentBeginningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum ukončenia zamestnania.
        /// </summary>
        internal static string ColumnEmploymentEndDate {
            get {
                return ResourceManager.GetString("ColumnEmploymentEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum prvéj udalosti.
        /// </summary>
        internal static string ColumnEventlogDateTimeFirst {
            get {
                return ResourceManager.GetString("ColumnEventlogDateTimeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum poslednej udalosti.
        /// </summary>
        internal static string ColumnEventlogDateTimeLast {
            get {
                return ResourceManager.GetString("ColumnEventlogDateTimeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov DCU.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov CCU.
        /// </summary>
        internal static string ColumnParent {
            get {
                return ResourceManager.GetString("ColumnParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba.
        /// </summary>
        internal static string ColumnPerson {
            get {
                return ResourceManager.GetString("ColumnPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobne ID.
        /// </summary>
        internal static string ColumnPersonID {
            get {
                return ResourceManager.GetString("ColumnPersonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav karty.
        /// </summary>
        internal static string ColumnState {
            get {
                return ResourceManager.GetString("ColumnState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefón.
        /// </summary>
        internal static string ColumnTelephone {
            get {
                return ResourceManager.GetString("ColumnTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximálny počet pripojených klientov.
        /// </summary>
        internal static string ConnectionCount {
            get {
                return ResourceManager.GetString("ConnectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCU.
        /// </summary>
        internal static string DCUText {
            get {
                return ResourceManager.GetString("DCUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dverné prostredie DCU.
        /// </summary>
        internal static string DoorEnvironmentForDCUName {
            get {
                return ResourceManager.GetString("DoorEnvironmentForDCUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dverné prostredie.
        /// </summary>
        internal static string DoorEnvironmentName {
            get {
                return ResourceManager.GetString("DoorEnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edícia.
        /// </summary>
        internal static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota nesmie byť prázdna.
        /// </summary>
        internal static string ErrorEmptyValue {
            get {
                return ResourceManager.GetString("ErrorEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počas vytvárania požiadavky došlo k chybe.
        /// </summary>
        internal static string ErrorOnCreateRequest {
            get {
                return ResourceManager.GetString("ErrorOnCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počas vytvárania požiadavky došlo k chybe (nepoadrilo sa získať CIID).
        /// </summary>
        internal static string ErrorOnCreateRequestCIID {
            get {
                return ResourceManager.GetString("ErrorOnCreateRequestCIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenie atribútu licencie zlyhalo (skontrolujte popisný súbor).
        /// </summary>
        internal static string ErrorOnLicenceProperty {
            get {
                return ResourceManager.GetString("ErrorOnLicenceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodarilo sa načítať potrebné licenčné informácie (certifikát, vlastnosti).
        ///(*.crt and *.ldsc súbory musia by prítomné).
        /// </summary>
        internal static string ErrorReadLicencePublisherAndProperties {
            get {
                return ResourceManager.GetString("ErrorReadLicencePublisherAndProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukončiť.
        /// </summary>
        internal static string FormLicenceRequest_buttonCancel {
            get {
                return ResourceManager.GetString("FormLicenceRequest_buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložiť.
        /// </summary>
        internal static string FormLicenceRequest_buttonSave {
            get {
                return ResourceManager.GetString("FormLicenceRequest_buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informácie o zákazníkovi.
        /// </summary>
        internal static string FormLicenceRequest_groupBoxCustomerInfo {
            get {
                return ResourceManager.GetString("FormLicenceRequest_groupBoxCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktný email.
        /// </summary>
        internal static string FormLicenceRequest_labelContactEmail {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktné meno.
        /// </summary>
        internal static string FormLicenceRequest_labelContactFirstName {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktné priezvisko.
        /// </summary>
        internal static string FormLicenceRequest_labelContactLastName {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktný telefón.
        /// </summary>
        internal static string FormLicenceRequest_labelContactPhone {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa zákazníka.
        /// </summary>
        internal static string FormLicenceRequest_labelCustAddr {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelCustAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno zákazníka.
        /// </summary>
        internal static string FormLicenceRequest_labelCustName {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelCustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požiadavka na licenciu.
        /// </summary>
        internal static string FormLicenceRequestFormLicenceRequest {
            get {
                return ResourceManager.GetString("FormLicenceRequestFormLicenceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povoliť.
        /// </summary>
        internal static string General_Enable {
            get {
                return ResourceManager.GetString("General_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavrieť.
        /// </summary>
        internal static string GeneralOptionsForm_bClose {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obnoviť.
        /// </summary>
        internal static string GeneralOptionsForm_bRefreshLicenceList {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bRefreshLicenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložiť.
        /// </summary>
        internal static string GeneralOptionsForm_bSave {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastaviť.
        /// </summary>
        internal static string GeneralOptionsForm_bSet {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES kryptovanie.
        /// </summary>
        internal static string GeneralOptionsForm_cbAESEnabled {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_cbAESEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preskočiť rekonfiguráciu databázy.
        /// </summary>
        internal static string GeneralOptionsForm_chbSaveAndSkipDB {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_chbSaveAndSkipDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenčný súbor.
        /// </summary>
        internal static string GeneralOptionsForm_labelLicenceFilePath {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_labelLicenceFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kľúč pre kryptovanie.
        /// </summary>
        internal static string GeneralOptionsForm_lAesEncryptionKey {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lAesEncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP port pre CNMP loockup.
        /// </summary>
        internal static string GeneralOptionsForm_lCnmpUdpPort {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lCnmpUdpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov servera.
        /// </summary>
        internal static string GeneralOptionsForm_lFriendlyName {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabindovať na špecifickú IP adresu.
        /// </summary>
        internal static string GeneralOptionsForm_lRemotingIpAddress {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lRemotingIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port pre vzdialený server.
        /// </summary>
        internal static string GeneralOptionsForm_lServerPort {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal Nova Server : Všeobecné nastavenia pre server.
        /// </summary>
        internal static string GeneralOptionsFormGeneralOptionsForm {
            get {
                return ResourceManager.GetString("GeneralOptionsFormGeneralOptionsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Táto možnosť je mienená hlavne pre zmeny licencií.
        ///    
        ///Naozaj chcete preskočiť rekonfiguráciu databázy ?.
        /// </summary>
        internal static string GeneralOptionsFormReallySkipDB {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReallySkipDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, zadajte platnú IP adresu.
        /// </summary>
        internal static string GeneralOptionsFormReenterIpAddress {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReenterIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, zadajte iný port pre vzdialený server.
        /// </summary>
        internal static string GeneralOptionsFormReenterRemotingServerPort {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReenterRemotingServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, zadajte iný UDP port pre CNMP loockup.
        /// </summary>
        internal static string GeneralOptionsFormReenterUdpPortForCNMP {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReenterUdpPortForCNMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP adresa nie je platná.
        /// </summary>
        internal static string GeneralOptionsFormServerIpAddressIsNotValid {
            get {
                return ResourceManager.GetString("GeneralOptionsFormServerIpAddressIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port nie je voľný.
        /// </summary>
        internal static string GeneralOptionsFormTcpPortIsNotFree {
            get {
                return ResourceManager.GetString("GeneralOptionsFormTcpPortIsNotFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP port nie je voľný.
        /// </summary>
        internal static string GeneralOptionsFormUdpPortIsNotFree {
            get {
                return ResourceManager.GetString("GeneralOptionsFormUdpPortIsNotFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavné nastavenia ešte nie sú nakonfigurované !
        ///
        ///Naozaj chcete zavrieť dialóg ?.
        /// </summary>
        internal static string GeneralOptionsFormUnconfiguredReallyContinue {
            get {
                return ResourceManager.GetString("GeneralOptionsFormUnconfiguredReallyContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Očakávaný typ je.
        /// </summary>
        internal static string GeneralRequestedType {
            get {
                return ResourceManager.GetString("GeneralRequestedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vstup.
        /// </summary>
        internal static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložený licenčný súbor neexistuje, alebo sa nenachádza v adresári servra.
        /// </summary>
        internal static string LicenseFileNotInServerDir {
            get {
                return ResourceManager.GetString("LicenseFileNotInServerDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložený licenčný súbor má nesprávnu príponu.
        /// </summary>
        internal static string LicenseFileWrongExtension {
            get {
                return ResourceManager.GetString("LicenseFileWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavná verzia servra.
        /// </summary>
        internal static string MajorVersion {
            get {
                return ResourceManager.GetString("MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povoliť prístupový plugin.
        /// </summary>
        internal static string NCASPluginEnabled {
            get {
                return ResourceManager.GetString("NCASPluginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bez expirácie.
        /// </summary>
        internal static string NoExpiration {
            get {
                return ResourceManager.GetString("NoExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie je špecifikované.
        /// </summary>
        internal static string NoSpecified {
            get {
                return ResourceManager.GetString("NoSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolenie importu z CSV/TSV.
        /// </summary>
        internal static string OfflineImport {
            get {
                return ResourceManager.GetString("OfflineImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výstup.
        /// </summary>
        internal static string OutputText {
            get {
                return ResourceManager.GetString("OutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal nova server je uz spustený. Zavrieť contal nova server?.
        /// </summary>
        internal static string QuestionCloseServer {
            get {
                return ResourceManager.GetString("QuestionCloseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal nova server je uz spustený. Zastaviť službu pre contal nova server?.
        /// </summary>
        internal static string QuestionStopService {
            get {
                return ResourceManager.GetString("QuestionStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požiadavka bola úspešne vytvorená.
        /// </summary>
        internal static string RequestSuccessfullyCreated {
            get {
                return ResourceManager.GetString("RequestSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všetko.
        /// </summary>
        internal static string SelectStructuredSubSiteForm_RootNode {
            get {
                return ResourceManager.GetString("SelectStructuredSubSiteForm_RootNode", resourceCulture);
            }
        }
    }
}
