//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Swedish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Swedish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.Server.Localization.Swedish", typeof(Localization_Swedish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åtkomstkontrolllista.
        /// </summary>
        internal static string AccessControlLists {
            get {
                return ResourceManager.GetString("AccessControlLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kortläsare.
        /// </summary>
        internal static string CardReaders {
            get {
                return ResourceManager.GetString("CardReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kort.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCU har föråldrad mjukvara.
        /// </summary>
        internal static string CCUOutdatedFirmware {
            get {
                return ResourceManager.GetString("CCUOutdatedFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin till Passersystem.
        /// </summary>
        internal static string CgpNCASServerplugin {
            get {
                return ResourceManager.GetString("CgpNCASServerplugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivera CIS integration.
        /// </summary>
        internal static string CISIntegration {
            get {
                return ResourceManager.GetString("CISIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Födelsedag.
        /// </summary>
        internal static string ColumnBD {
            get {
                return ResourceManager.GetString("ColumnBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullständigt kortnummer.
        /// </summary>
        internal static string ColumnCardFullNumber {
            get {
                return ResourceManager.GetString("ColumnCardFullNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korthållare.
        /// </summary>
        internal static string ColumnCardHolder {
            get {
                return ResourceManager.GetString("ColumnCardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kortnummer.
        /// </summary>
        internal static string ColumnCardNumber {
            get {
                return ResourceManager.GetString("ColumnCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Från.
        /// </summary>
        internal static string ColumnDateFrom {
            get {
                return ResourceManager.GetString("ColumnDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        internal static string ColumnDateTo {
            get {
                return ResourceManager.GetString("ColumnDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avdelning.
        /// </summary>
        internal static string ColumnDepartment {
            get {
                return ResourceManager.GetString("ColumnDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivning.
        /// </summary>
        internal static string ColumnDescription {
            get {
                return ResourceManager.GetString("ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ColumnEmail {
            get {
                return ResourceManager.GetString("ColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anställningens startdatum.
        /// </summary>
        internal static string ColumnEmploymentBeginningDate {
            get {
                return ResourceManager.GetString("ColumnEmploymentBeginningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutdatum för anställning.
        /// </summary>
        internal static string ColumnEmploymentEndDate {
            get {
                return ResourceManager.GetString("ColumnEmploymentEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string ColumnPerson {
            get {
                return ResourceManager.GetString("ColumnPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personligt ID.
        /// </summary>
        internal static string ColumnPersonID {
            get {
                return ResourceManager.GetString("ColumnPersonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat.
        /// </summary>
        internal static string ColumnState {
            get {
                return ResourceManager.GetString("ColumnState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string ColumnTelephone {
            get {
                return ResourceManager.GetString("ColumnTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximalt antal anslutna klienter.
        /// </summary>
        internal static string ConnectionCount {
            get {
                return ResourceManager.GetString("ConnectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCU har föråldrad mjukvara.
        /// </summary>
        internal static string DCUOutdatedFirmware {
            get {
                return ResourceManager.GetString("DCUOutdatedFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCU.
        /// </summary>
        internal static string DCUText {
            get {
                return ResourceManager.GetString("DCUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max antal dörrmiljöer.
        /// </summary>
        internal static string DoorEnvironmentCount {
            get {
                return ResourceManager.GetString("DoorEnvironmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dörrmiljö DCU.
        /// </summary>
        internal static string DoorEnvironmentForDCUName {
            get {
                return ResourceManager.GetString("DoorEnvironmentForDCUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dörrmiljö.
        /// </summary>
        internal static string DoorEnvironmentName {
            get {
                return ResourceManager.GetString("DoorEnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Värdet kan inte vara tomt.
        /// </summary>
        internal static string ErrorEmptyValue {
            get {
                return ResourceManager.GetString("ErrorEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej giltlig anslutningssträng till databasen.
        /// </summary>
        internal static string ErrorNotValidConnectionString {
            get {
                return ResourceManager.GetString("ErrorNotValidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel uppstod då förfrågan skapades.
        /// </summary>
        internal static string ErrorOnCreateRequest {
            get {
                return ResourceManager.GetString("ErrorOnCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel uppstod då förfrågan skapades (kunde inte hämta CIID).
        /// </summary>
        internal static string ErrorOnCreateRequestCIID {
            get {
                return ResourceManager.GetString("ErrorOnCreateRequestCIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange licens egenskaper misslyckades (se beskrivande fil).
        /// </summary>
        internal static string ErrorOnLicenceProperty {
            get {
                return ResourceManager.GetString("ErrorOnLicenceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det gick inte att ladda in nödvändig licensinformation (certifikat, egenskaper).
        ///(*.crt och *.ldsc fil måste finnas tillgänglig).
        /// </summary>
        internal static string ErrorReadLicencePublisherAndProperties {
            get {
                return ResourceManager.GetString("ErrorReadLicencePublisherAndProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string FormLicenceRequest_buttonCancel {
            get {
                return ResourceManager.GetString("FormLicenceRequest_buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        internal static string FormLicenceRequest_buttonSave {
            get {
                return ResourceManager.GetString("FormLicenceRequest_buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kund information.
        /// </summary>
        internal static string FormLicenceRequest_groupBoxCustomerInfo {
            get {
                return ResourceManager.GetString("FormLicenceRequest_groupBoxCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt e-post.
        /// </summary>
        internal static string FormLicenceRequest_labelContactEmail {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt förnamn.
        /// </summary>
        internal static string FormLicenceRequest_labelContactFirstName {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt efternamn.
        /// </summary>
        internal static string FormLicenceRequest_labelContactLastName {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt telefon.
        /// </summary>
        internal static string FormLicenceRequest_labelContactPhone {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kund adress.
        /// </summary>
        internal static string FormLicenceRequest_labelCustAddr {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelCustAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kund namn.
        /// </summary>
        internal static string FormLicenceRequest_labelCustName {
            get {
                return ResourceManager.GetString("FormLicenceRequest_labelCustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensförfrågan.
        /// </summary>
        internal static string FormLicenceRequestFormLicenceRequest {
            get {
                return ResourceManager.GetString("FormLicenceRequestFormLicenceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivera.
        /// </summary>
        internal static string General_Enable {
            get {
                return ResourceManager.GetString("General_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stäng.
        /// </summary>
        internal static string GeneralOptionsForm_bClose {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppdatera.
        /// </summary>
        internal static string GeneralOptionsForm_bRefreshLicenceList {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bRefreshLicenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        internal static string GeneralOptionsForm_bSave {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange.
        /// </summary>
        internal static string GeneralOptionsForm_bSet {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_bSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES Remoting.
        /// </summary>
        internal static string GeneralOptionsForm_cbAESEnabled {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_cbAESEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoppa över omkonfigurering av databas.
        /// </summary>
        internal static string GeneralOptionsForm_chbSaveAndSkipDB {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_chbSaveAndSkipDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licens fil.
        /// </summary>
        internal static string GeneralOptionsForm_labelLicenceFilePath {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_labelLicenceFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aes krypteringsnyckel.
        /// </summary>
        internal static string GeneralOptionsForm_lAesEncryptionKey {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lAesEncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP port för CNMP sökning.
        /// </summary>
        internal static string GeneralOptionsForm_lCnmpUdpPort {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lCnmpUdpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servernamn.
        /// </summary>
        internal static string GeneralOptionsForm_lFriendlyName {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind till specifik IP adress.
        /// </summary>
        internal static string GeneralOptionsForm_lRemotingIpAddress {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lRemotingIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjärrserverport.
        /// </summary>
        internal static string GeneralOptionsForm_lServerPort {
            get {
                return ResourceManager.GetString("GeneralOptionsForm_lServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal Nova Server: Globala inställningar för server.
        /// </summary>
        internal static string GeneralOptionsFormGeneralOptionsForm {
            get {
                return ResourceManager.GetString("GeneralOptionsFormGeneralOptionsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detta val är ämnat i huvudsak för förändring av licens
        /// 
        ///Vill Ni verkligen hoppa över omkonfigurering av databas?.
        /// </summary>
        internal static string GeneralOptionsFormReallySkipDB {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReallySkipDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen ange IP adressen en gång till.
        /// </summary>
        internal static string GeneralOptionsFormReenterIpAddress {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReenterIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen ange fjärrserverport en gång till.
        /// </summary>
        internal static string GeneralOptionsFormReenterRemotingServerPort {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReenterRemotingServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen ange UDP port för CNMP sökning.
        /// </summary>
        internal static string GeneralOptionsFormReenterUdpPortForCNMP {
            get {
                return ResourceManager.GetString("GeneralOptionsFormReenterUdpPortForCNMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltlig IP adress.
        /// </summary>
        internal static string GeneralOptionsFormServerIpAddressIsNotValid {
            get {
                return ResourceManager.GetString("GeneralOptionsFormServerIpAddressIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej möjligt att få tillgång till registret !
        /// 
        ///Kontrollera att Ni kör konfigureringsläget som administratör.
        /// </summary>
        internal static string GeneralOptionsFormServerNoRegistryWriteAccess {
            get {
                return ResourceManager.GetString("GeneralOptionsFormServerNoRegistryWriteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port är ej ledig.
        /// </summary>
        internal static string GeneralOptionsFormTcpPortIsNotFree {
            get {
                return ResourceManager.GetString("GeneralOptionsFormTcpPortIsNotFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP port är ej ledig.
        /// </summary>
        internal static string GeneralOptionsFormUdpPortIsNotFree {
            get {
                return ResourceManager.GetString("GeneralOptionsFormUdpPortIsNotFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globala inställningar är inte konfigurerade!
        ///
        ///Vill Ni verkligen stänga dialogfönstret?.
        /// </summary>
        internal static string GeneralOptionsFormUnconfiguredReallyContinue {
            get {
                return ResourceManager.GetString("GeneralOptionsFormUnconfiguredReallyContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förfrågad sort är.
        /// </summary>
        internal static string GeneralRequestedType {
            get {
                return ResourceManager.GetString("GeneralRequestedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID management/Batch design.
        /// </summary>
        internal static string IdManagement {
            get {
                return ResourceManager.GetString("IdManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingång.
        /// </summary>
        internal static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparad licensfil finns ej eller finns inte i servermappen.
        /// </summary>
        internal static string LicenseFileNotInServerDir {
            get {
                return ResourceManager.GetString("LicenseFileNotInServerDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparad licensfil har felaktig ändelse.
        /// </summary>
        internal static string LicenseFileWrongExtension {
            get {
                return ResourceManager.GetString("LicenseFileWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server huvudversion.
        /// </summary>
        internal static string MajorVersion {
            get {
                return ResourceManager.GetString("MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägsta mjukvaruversion som stöds.
        /// </summary>
        internal static string MinimalSupportedFW {
            get {
                return ResourceManager.GetString("MinimalSupportedFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivera plugin till passersystem.
        /// </summary>
        internal static string NCASPluginEnabled {
            get {
                return ResourceManager.GetString("NCASPluginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inget utgångsdatum.
        /// </summary>
        internal static string NoExpiration {
            get {
                return ResourceManager.GetString("NoExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej angivet.
        /// </summary>
        internal static string NoSpecified {
            get {
                return ResourceManager.GetString("NoSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivera import från CSV/TSV.
        /// </summary>
        internal static string OfflineImport {
            get {
                return ResourceManager.GetString("OfflineImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utgång.
        /// </summary>
        internal static string OutputText {
            get {
                return ResourceManager.GetString("OutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal Nova server körs redan. Avsluta Contal Nova server?.
        /// </summary>
        internal static string QuestionCloseServer {
            get {
                return ResourceManager.GetString("QuestionCloseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contal Nova server körs redan. Stoppa tjänsten för Contal Nova server?.
        /// </summary>
        internal static string QuestionStopService {
            get {
                return ResourceManager.GetString("QuestionStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapandet av förfrågan lyckades.
        /// </summary>
        internal static string RequestSuccessfullyCreated {
            get {
                return ResourceManager.GetString("RequestSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allt.
        /// </summary>
        internal static string SelectStructuredSubSiteForm_RootNode {
            get {
                return ResourceManager.GetString("SelectStructuredSubSiteForm_RootNode", resourceCulture);
            }
        }
    }
}
