using System;

using Contal.IwQuick.Data;

namespace Contal.Cgp.Globals
{
    public enum MethodNames
    {
        GetIsConfigured,
        Configure,
        Upgrade,
        UnsetUpgradeMode,
        Unconfigure,
        StartTFTPServer,
        StartTFTPServerWithEdit,
        StopTFTPServer,
        ConfigureForAnotherClient,
        IsCcuConfiguredServerOnline,
        Reset,
        SoftReset,
        CommunicationStatistic,
        ResetSended,
        ResetDeserializationError,
        ResetReceived,
        ResetReceivedError,
        ResetCommunicationStatistic,
        ResetMsgRetry,
        GetCcuStartsCount,
        ResetCcuStartCounter,
        WinCEImageVersion,
        CoprocessorBuildNumberStatistics,
        ResultSimulationCardSwiped,
        ExistsPathOrFile,
        ForceReconfiguration,
        SendAllStatesToServer,
        SaveObject,
        ReadMaximumVersionAndIds,
        SaveMaxObjectTypeVersion,
        DeleteObject,
        ApplyChanges,
        DeleteEvent,
        DeleteEvents,
        GetInputCount,
        GetMacAddress,
        GetMainBoardType,
        GetCcuFirmwareVersion,
        GetInputState,
        GetOutputCount,
        GetDoorEnvironmentsCount,
        DoorEnvironmentAccessGranted,
        GetAlarmAreaActualState,
        GetAlarmAreaActivationState,
        SetAlarmArea,
        UnconditionalSetAlarmArea,
        UnsetAlarmArea,
        FileExists,
        ContainsDCUUpgradePackageVersion,
        GetAvailableDCUUpgrades,
        EnsureDirectory,
        SetDefaultDCUUpgradeVersion,
        UpgradeDCUs,
        RegisterDCUsForUpgradeVersion,
        RegisterCRsForUpgradeVersion,
        GetIPSettings,
        ResetDcu,
        RequestDcuMemoryLoad,
        SetIPSettings,
        IsCCU0,
        IsCCUUpgrader,
        GetCurrentTime,
        AcknowledgeAllowed,
        SaveConfigurePassword,
        CompareConfigurePassword,
        IsSetConfigurePassword,
        StartSaveCardAccessForCardReaders,
        DeleteCardAccessForCardReaders,
        StopSaveCardAccessForCardReaders,
        AuthenticateClient,
        DummyMethod,
        SaveEvent,
        CcuCoreRemotingProviderSaveEvent,
        CCUConfiguredStateChanged,
        SetOldEventsSettings,
        SendUpsMonitorData,
        StopSendUpsMonitorData,
        ObtainDcuRunningTestStates,
        SendDcuRoutinTestConfiguration,
        StartSaveAclPersonsToCCU,
        StopSaveAclPersonsToCCU,
        SetNTPTimeDifferenceTolerance,
        StartSaveCards,
        StopSaveCards,
        DeleteACLPerson,
        GetOtherStatistics,
        ResetCardReader,
        SetTimeManually,
        DeleteAllEvents,
        GetAllBlockFilesInfo,
        ResetBlockFilesInfo,
        SetMaxEventsCount,
        SetTimeSyncingFromServer,
        SetTimeFromServer,
        GetThreadsInfo,
        GetVerbosityLevelsInfo,
        SetVerbosityLevel,
        GetVerbosityLevel,
        ResetCCUCommandTimeouts,
        SetEnableLoggingSDPSTZChanges,
        SetAllowPINCachingInCardReaderMenu,
        WaitForFinishProcessingStream,
        SendBindings,
        CcuCoreRemotingProviderCcuConfiguredStateChanged,
        GetCardsInZone,
        RemoveCardsFromAntiPassBackZone,
        IsCat12Combo,
        HasCat12ComboLicence,
        SetCat12ComboLicence,
        SetAllowCodeLength,
        SetPinConfirmationObligatory
    }

    [LwSerialize(111)]
    [Serializable]
    public enum EventType : byte
    {
        InputStateChanged = 0,
        OutputStateChanged = 1,
        DcuCommandTimeOut = 2,
        DSMAccessPermitted = 3,
        DSMAccessInterupted = 4,
        DSMAccessViolated = 5,
        DSMApasRestored = 6,
        DcuCommandNotACK = 7,
        DSMStateChanged = 8,
        AlarmAreaAlarmStateChanged = 9,
        DcuNodeReleased = 10,
        AlarmAreaActivationStateChanged = 11,
        DcuNodeRenewed = 12,
        DSMAccessRestricted = 13,
        CardReaderOnlineStateChanged = 14,
        DcuNodeAssigned = 15,
        DcuOnlineStateChanged = 16,
        AccessDeniedCardBlockedOrInactive = 17,
        AccessDeniedInvalidCode = 18,
        AccessDeniedInvalidEmergencyCode = 19,
        AccessDeniedInvalidPin = 20,
        AccessDenied = 21,
        UnknownCard = 22,
        AccessDeniedSetAlarmAreaInvalidCode = 24,
        AccessDeniedUnsetAlarmAreaInvalidCode = 25,
        AccessDeniedSetAlarmAreaInvalidPin = 26,
        AccessDeniedUnsetAlarmAreaInvalidPin = 27,
        AccessDeniedSetAlarmAreaNoRights = 28,
        AccessDeniedUnsetAlarmAreaNoRights = 29,
        SetAlarmAreaFromCardReader = 30,
        UnsetAlarmAreaFromCardReader = 31,
        OutputRealStateChanged = 32,
        SensorInAlarmCount = 34,
        AcknowledgeInputAlarm = 35,
        CardReaderCommandChanged = 37,
        CardReaderLastCardChanged = 38,
        SendTamper = 39,
        CcuActualTimeSent = 40,
        CCUTFTPFileReceived = 41,
        CcuUpgradeFileUnpackProgress = 42,
        CCUUpgraderStartFailed = 43,
        CEUpgradeFinished = 44,
        DcuOutputCount = 45,
        DcuFirmwareVersion = 46,
        DcuMemoryWarning = 47,
        CRUpgradePercentageSet = 48,
        CRUpgradeResultSet = 49,
        DcuInputCount = 50,
        DcuPhysicalAddressChanged = 51,
        DcuUpgradePercentageSet = 52,
        ProcessDCUUpgradePackageFailed = 53,
        ProcessCRUpgradePackageFailed = 54,
        DSMNormalAccess = 55,
        AlarmAreaAlarmStateChangeAlarm = 56,
        UpsOnlineStateChanged = 57,
        UpsAlarmStateChanged = 58,
        UpsValuesChanged = 59,
        SetAlarmAreaByObjectForAutomaticActivation = 60,
        UnsetAlarmAreaByObjectForAutomaticActivation = 61,
        SectorCardSystemAdded = 63,
        SectorCardSystemRemoved = 64,
        AlarmCCUPrimaryPowerMissing = 65,
        AlarmCCUBatteryIsLow = 66,
        AlarmCCUExtFuse = 67,
        RunMethodFailed = 69,
        SecurityTimeChannelChanged = 70,
        CoprocessorFailureChanged = 71,
        CCUTimeAdjusted = 72,
        ObjectDeserializeFailed = 73,
        CCUTimingProblem = 74,
        GetFromDatabaseReturnNull = 75,
        CCUIncomingTransferInfo = 76,
        NotConfirmSetUnsetAAFromEIS = 77,
        AlarmAreaRequestActivationState = 78,
        ICCUSendingOfObjectStateFailed = 79,
        ICCUPortAlreadyUsed = 80,
        AlarmAreaSetFromCRFailed = 81,

        AlarmAreaSabotageStateChanged = 83,
        DcuInputsSabotage = 84,
        ExceptionOccurred = 85,
        CCUMemoryLoadStateChanged = 86,
        CCUFilesystemProblem = 87,
        CCUSdCardNotFound = 88,
        AlarmAreaBoughtTimeChanged = 89,
        AlarmAreaTimeBuyingFailed = 90,
        AlarmAreaBoughtTimeExpired = 91,
        AntiPassBackZoneCardEntered = 92,
        AntiPassBackZoneCardExited = 93,
        AntiPassBackZoneCardTimedOut = 94,
        AntiPassBackZoneCardAlreadyPresent = 95,

        FunctionKeyPressed = 97,

        SetAlarmAreaFromClient = 98,
        UnsetAlarmAreaFromClient = 99,

        InputStateInfo = 101,
        AlarmAreaAlarmStateInfo = 102,
        AlarmAreaSabotageStateInfo = 103,
        CardReaderOnlineStateInfo = 105,
        TamperInfo = 107,

        AutonomousRunEventsFilesPrepared = 108,
        AutonomousRunEventFileProcessed = 109,

        AlarmOccuredOrChanged = 110,

        AlarmCcuUpsOutputFuse = 111,
        AlarmCcuUpsBatteryFault = 112,
        AlarmCcuUpsBatteryFuse = 113,
        AlarmCcuUpsOvertemperature = 114,
        AlarmCcuUpsTamperSabotage = 115,
        
        AccessDeniedEnterToAaMenuInvalidPin = 117,
        AccessDeniedEnterToAaMenuInvalidCode = 118,
        AccessDeniedEnterToSensorsMenuInvalidPin = 119,
        AccessDeniedEnterToSensorsMenuInvalidCode = 120,
        AccessDeniedEnterToEventlogsMenuInvalidPin = 121,
        AccessDeniedEnterToEventlogsMenuInvalidCode = 122,

        AlarmAreaSensorBlockingTypeChanged = 123,
        AlarmAreaSensorBlockingTypeInfo = 124,
        AlarmAreaSensorStateChanged = 125,
        AlarmAreaSensorAlarmAcknowledged = 126,
        AlarmAreaSensorStateInfo = 127,
        AlarmAreaSensorStateChangedOnlyForCardReader = 128,

        InvalidPinRetriesLimitReached = 129,
        CardReaderBlockedStateChanged = 130,

        TimeBuingMatrixStateChangedInfo = 131
    }

    [Serializable]
    public enum SymbolType
    {
        CardReader,
        Siren,
        IrDetector,
        MagneticsContact,
        DoorEnviromentLeft,
        DoorEnviromentRight,
        AlarmArea,
        AlarmButton,
        GlassbreakDetector,
        AlarmGlass,
        CapacitiveSensor,
        OpticalIndication,
        Loudspeaker,
        PushButton, 
        ElectricStrike,
        ElectricLock,
        MotorizedLock,
        SmokeDetector,
        CcuC,
        CcuUC,
        CcuH4C,
        CcuH4UC,
        DcuDC,
        DcuH4DC
    }

    [LwSerialize(112)]
    public enum State : byte
    {
        Off = 0,
        On = 1,
        Tamper = 2,
        Unset = 3,
        Set = 4,
        Alarm = 5,
        Prewarning = 6,
        BuyTime = 7,
        TemporaryUnsetEntry = 8,
        TemporaryUnsetExit = 9,
        unlocked = 10,
        locked = 11,
        card = 12,
        cardpin = 13,
        code = 14,
        codecard = 15,
        codecardpin = 16,
        togglecard = 17,
        togglecardpin = 18,
        Normal = 19,
        Short = 20,
        Break = 21,
        Unknown = 22,
        unlocking = 23,
        opened = 24,
        intrusion = 25,
        sabotage = 26,
        ajarPrewarning = 27,
        ajar = 28,
        UnsetBoughtTime = 29,
        Online = 30,
        Offline = 31,
        Upgrading = 32,
        WaitingForUpgrade = 33,
        AutoUpgrading = 34,
        Reseting = 35,
        locking = 36,
        Acknowledge = 37,
        AcknowledgeAndBlock = 38,
        Block = 39,
        UnconditionaSet = 40,
        UsedByAnotherAplication = 41,
        OutOfRange = 42
    }
}
