using Contal.IwQuick.Data;

namespace Contal.Cgp.Globals
{
    [LwSerialize(110)]
    public enum ObjectType
    {
        DailyPlan = 0,
        TimeZone = 1,
        Calendar = 2,
        CalendarDateSetting = 3,
        DayInterval = 4,
        TimeZoneDateSetting = 5,
        SecurityDayInterval = 6,
        SecurityDailyPlan = 7,
        DayType = 8,
        Output = 10,
        Input = 11,
        ACLSetting = 12,
        ACLSettingAA = 13,
        ACLPerson = 14,
        AccessControlList = 15,
        Card = 16,
        CardSystem = 17,
        AlarmArea = 18,
        AACardReader = 19,
        AccessZone = 20,
        CCU = 21,
        AAInput = 22,
        DCU = 23,
        DoorEnvironment = 24,
        CardReader = 25,
        DevicesAlarmSetting = 26,
        Person = 27,
        SecurityTimeZone = 28,
        SecurityTimeZoneDateSetting = 29,
        MifareSectorData = 30,
        ACLGroup = 31,
        AntiPassBackZone = 32,
        Login = 101,
        AccessControl = 102,
        PresentationGroup = 103,
        SecuritySetting = 104,
        SystemEvent = 105,
        CisNGGroup = 106,
        PresentationFormatter = 107,
        CisNG = 108,
        CustomAccessControl = 109,
        Eventlog = 110,
        UserFoldersStructure = 111,
        UserFoldersStructureObject = 112,
        CentralNameRegister = 113,
        ServerGeneralOptionsDB = 114,
        AlarmPriority = 115,
        CSVImportColumn = 116,
        CSVImportSchema = 117,
        GlobalAlarmInstruction = 118,
        RelationshipGlobalAlarmInstructionObject = 119,
        CardTemplate = 120,
        CardPair = 121,
        LoginGroup = 122,
        StructuredSubSite = 123,
        StructuredSubSiteObject = 124,
        Scene = 125,
        GraphicSymbol = 126,
        GraphicSymbolRawData = 127,
        GraphicSymbolTemplate = 128,
        MultiDoor = 129,
        MultiDoorElement = 130,
        Floor = 131,
        GraphicsView = 132,
        AlarmTransmitter = 133,
        AlarmArc = 134,
        DevicesAlarmSettingAlarmArc = 135,
        AlarmAreaAlarmArc = 136,
        CcuAlarmArc = 137,
        CardReaderAlarmArc = 138,
        DcuAlarmArc = 139,
        DoorEnvironmentAlarmArc = 140,
        TimetecSetting = 141,

        PersonAttribute = 142,
        ReportSetting = 143,

        NotSupport = 201,
        AllObjectTypes = 202
    }   
}
