/*  
 *   File: LonNvTypes.h
 *   Generated by LonTalk Interface Developer 4.00.11
 *
 *   Created on Mon May 14 09:10:26 2012
 *   This file applies to the device with program ID 9F:FF:FF:00:00:00:04:00
 *
 *   Copyright (c) Echelon Corporation 2002-2009
 *   All rights reserved.
 *
 *   This file is Example Software as defined in the Software
 *   License Agreement that governs its use.
 *
 *   ECHELON MAKES NO REPRESENTATION, WARRANTY, OR CONDITION OF
 *   ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE OR IN
 *   ANY COMMUNICATION WITH YOU, INCLUDING, BUT NOT LIMITED TO,
 *   ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY
 *   QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE, 
 *   NONINFRINGEMENT, AND THEIR EQUIVALENTS.
 */
#if !defined(DEFINED_LONNVTYPES_H)
#define DEFINED_LONNVTYPES_H

/*
 *  Make sure to enforce a packing of 1, and a padding of 0,
 *  when compiling these type definitions. Please consult your
 *  compiler's manual for details on structure packing and padding.
 */


/* 
 *  Type: SCPTnwrkCnfg
 */
typedef ncsInt SCPTnwrkCnfg;


/* 
 *  Type: SNVT_obj_request
 */
typedef LON_STRUCT_BEGIN(SNVT_obj_request)
{
    ncuLong object_id;
    ncsInt object_request;
} LON_STRUCT_END(SNVT_obj_request);


/* 
 *  Type: SNVT_obj_status
 */
typedef LON_STRUCT_BEGIN(SNVT_obj_status)
{
    ncuLong object_id;
    LonByte  Flags_1;   /* Use bit field macros, defined below */
    LonByte  Flags_2;   /* Use bit field macros, defined below */
    LonByte  Flags_3;   /* Use bit field macros, defined below */
    LonByte  Flags_4;   /* Use bit field macros, defined below */
} LON_STRUCT_END(SNVT_obj_status);


/*
 *  Macros to access the invalid_id bit field contained in Flags_1
 */
#define LON_INVALIDID_MASK  0x80
#define LON_INVALIDID_SHIFT 7
#define LON_INVALIDID_FIELD Flags_1

/*
 *  Macros to access the invalid_request bit field contained in Flags_1
 */
#define LON_INVALIDREQUEST_MASK  0x40
#define LON_INVALIDREQUEST_SHIFT 6
#define LON_INVALIDREQUEST_FIELD Flags_1

/*
 *  Macros to access the disabled bit field contained in Flags_1
 */
#define LON_DISABLED_MASK  0x20
#define LON_DISABLED_SHIFT 5
#define LON_DISABLED_FIELD Flags_1

/*
 *  Macros to access the out_of_limits bit field contained in Flags_1
 */
#define LON_OUTOFLIMITS_MASK  0x10
#define LON_OUTOFLIMITS_SHIFT 4
#define LON_OUTOFLIMITS_FIELD Flags_1

/*
 *  Macros to access the open_circuit bit field contained in Flags_1
 */
#define LON_OPENCIRCUIT_MASK  0x08
#define LON_OPENCIRCUIT_SHIFT 3
#define LON_OPENCIRCUIT_FIELD Flags_1

/*
 *  Macros to access the out_of_service bit field contained in Flags_1
 */
#define LON_OUTOFSERVICE_MASK  0x04
#define LON_OUTOFSERVICE_SHIFT 2
#define LON_OUTOFSERVICE_FIELD Flags_1

/*
 *  Macros to access the mechanical_fault bit field contained in Flags_1
 */
#define LON_MECHANICALFAULT_MASK  0x02
#define LON_MECHANICALFAULT_SHIFT 1
#define LON_MECHANICALFAULT_FIELD Flags_1

/*
 *  Macros to access the feedback_failure bit field contained in Flags_1
 */
#define LON_FEEDBACKFAILURE_MASK  0x01
#define LON_FEEDBACKFAILURE_SHIFT 0
#define LON_FEEDBACKFAILURE_FIELD Flags_1

/*
 *  Macros to access the over_range bit field contained in Flags_2
 */
#define LON_OVERRANGE_MASK  0x80
#define LON_OVERRANGE_SHIFT 7
#define LON_OVERRANGE_FIELD Flags_2

/*
 *  Macros to access the under_range bit field contained in Flags_2
 */
#define LON_UNDERRANGE_MASK  0x40
#define LON_UNDERRANGE_SHIFT 6
#define LON_UNDERRANGE_FIELD Flags_2

/*
 *  Macros to access the electrical_fault bit field contained in Flags_2
 */
#define LON_ELECTRICALFAULT_MASK  0x20
#define LON_ELECTRICALFAULT_SHIFT 5
#define LON_ELECTRICALFAULT_FIELD Flags_2

/*
 *  Macros to access the unable_to_measure bit field contained in Flags_2
 */
#define LON_UNABLETOMEASURE_MASK  0x10
#define LON_UNABLETOMEASURE_SHIFT 4
#define LON_UNABLETOMEASURE_FIELD Flags_2

/*
 *  Macros to access the comm_failure bit field contained in Flags_2
 */
#define LON_COMMFAILURE_MASK  0x08
#define LON_COMMFAILURE_SHIFT 3
#define LON_COMMFAILURE_FIELD Flags_2

/*
 *  Macros to access the fail_self_test bit field contained in Flags_2
 */
#define LON_FAILSELFTEST_MASK  0x04
#define LON_FAILSELFTEST_SHIFT 2
#define LON_FAILSELFTEST_FIELD Flags_2

/*
 *  Macros to access the self_test_in_progress bit field contained in Flags_2
 */
#define LON_SELFTESTINPROGRESS_MASK  0x02
#define LON_SELFTESTINPROGRESS_SHIFT 1
#define LON_SELFTESTINPROGRESS_FIELD Flags_2

/*
 *  Macros to access the locked_out bit field contained in Flags_2
 */
#define LON_LOCKEDOUT_MASK  0x01
#define LON_LOCKEDOUT_SHIFT 0
#define LON_LOCKEDOUT_FIELD Flags_2

/*
 *  Macros to access the manual_control bit field contained in Flags_3
 */
#define LON_MANUALCONTROL_MASK  0x80
#define LON_MANUALCONTROL_SHIFT 7
#define LON_MANUALCONTROL_FIELD Flags_3

/*
 *  Macros to access the in_alarm bit field contained in Flags_3
 */
#define LON_INALARM_MASK  0x40
#define LON_INALARM_SHIFT 6
#define LON_INALARM_FIELD Flags_3

/*
 *  Macros to access the in_override bit field contained in Flags_3
 */
#define LON_INOVERRIDE_MASK  0x20
#define LON_INOVERRIDE_SHIFT 5
#define LON_INOVERRIDE_FIELD Flags_3

/*
 *  Macros to access the report_mask bit field contained in Flags_3
 */
#define LON_REPORTMASK_MASK  0x10
#define LON_REPORTMASK_SHIFT 4
#define LON_REPORTMASK_FIELD Flags_3

/*
 *  Macros to access the programming_mode bit field contained in Flags_3
 */
#define LON_PROGRAMMINGMODE_MASK  0x08
#define LON_PROGRAMMINGMODE_SHIFT 3
#define LON_PROGRAMMINGMODE_FIELD Flags_3

/*
 *  Macros to access the programming_fail bit field contained in Flags_3
 */
#define LON_PROGRAMMINGFAIL_MASK  0x04
#define LON_PROGRAMMINGFAIL_SHIFT 2
#define LON_PROGRAMMINGFAIL_FIELD Flags_3

/*
 *  Macros to access the alarm_notify_disabled bit field contained in Flags_3
 */
#define LON_ALARMNOTIFYDISABLED_MASK  0x02
#define LON_ALARMNOTIFYDISABLED_SHIFT 1
#define LON_ALARMNOTIFYDISABLED_FIELD Flags_3

/*
 *  Macros to access the reset_complete bit field contained in Flags_3
 */
#define LON_RESETCOMPLETE_MASK  0x01
#define LON_RESETCOMPLETE_SHIFT 0
#define LON_RESETCOMPLETE_FIELD Flags_3

/*
 *  Macros to access the reserved2 bit field contained in Flags_4
 */
#define LON_RESERVED2_MASK  0xFF
#define LON_RESERVED2_SHIFT 0
#define LON_RESERVED2_FIELD Flags_4


/* 
 *  Type: SNVT_switch
 */
typedef LON_STRUCT_BEGIN(SNVT_switch)
{
    ncuInt value;
    ncsInt state;
} LON_STRUCT_END(SNVT_switch);

#endif  /* defined(DEFINED_LONNVTYPES_H) */
/* end of file. */
