//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.NCAS.CCU.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Localization_Swedish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Localization_Swedish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.NCAS.CCU.Localization.Localization.Swedish", typeof(Localization_Swedish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon kan inte tillkopplas. Sektioner i larm..
        /// </summary>
        internal static string AAcannotBeSet {
            get {
                return ResourceManager.GetString("AAcannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera.
        /// </summary>
        internal static string Acknowledge {
            get {
                return ResourceManager.GetString("Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvitt. och blockera.
        /// </summary>
        internal static string AcknowledgeAndBlock {
            get {
                return ResourceManager.GetString("AcknowledgeAndBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvitterad.
        /// </summary>
        internal static string Acknowledged {
            get {
                return ResourceManager.GetString("Acknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera sektions larm.
        /// </summary>
        internal static string AcknowledgeInputAlarm {
            get {
                return ResourceManager.GetString("AcknowledgeInputAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larm.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon.
        /// </summary>
        internal static string AlarmArea {
            get {
                return ResourceManager.GetString("AlarmArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon status ändrad larm.
        /// </summary>
        internal static string AlarmAreaAlarmStateChangeAlarm {
            get {
                return ResourceManager.GetString("AlarmAreaAlarmStateChangeAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon larmstatus ändrad.
        /// </summary>
        internal static string AlarmAreaAlarmStateChanged {
            get {
                return ResourceManager.GetString("AlarmAreaAlarmStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon köpt tid ändrad.
        /// </summary>
        internal static string AlarmAreaBoughtTimeChanged {
            get {
                return ResourceManager.GetString("AlarmAreaBoughtTimeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon köpt tid utgånget.
        /// </summary>
        internal static string AlarmAreaBoughtTimeExpired {
            get {
                return ResourceManager.GetString("AlarmAreaBoughtTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon kan inte tillkopplas, vissa sektioner är i larm.
        /// </summary>
        internal static string AlarmAreaCanNotBeSet {
            get {
                return ResourceManager.GetString("AlarmAreaCanNotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon har larmat under tillkopplingsperioden..
        /// </summary>
        internal static string AlarmAreaHasBeenInAlarmStateDuringSetPeriod {
            get {
                return ResourceManager.GetString("AlarmAreaHasBeenInAlarmStateDuringSetPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon sabotage status ändrad.
        /// </summary>
        internal static string AlarmAreaSabotageStateChanged {
            get {
                return ResourceManager.GetString("AlarmAreaSabotageStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektion kvitterad.
        /// </summary>
        internal static string AlarmAreaSensorAlarmAcknowledged {
            get {
                return ResourceManager.GetString("AlarmAreaSensorAlarmAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektions blockeringsstatus ändrad.
        /// </summary>
        internal static string AlarmAreaSensorBlockingTypeChanged {
            get {
                return ResourceManager.GetString("AlarmAreaSensorBlockingTypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektions status ändrad.
        /// </summary>
        internal static string AlarmAreaSensorStateChangedOnlyForCardReader {
            get {
                return ResourceManager.GetString("AlarmAreaSensorStateChangedOnlyForCardReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla larmzon misslyckades..
        /// </summary>
        internal static string AlarmAreaSetFailed {
            get {
                return ResourceManager.GetString("AlarmAreaSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon tillkoppla från KL misslyckades.
        /// </summary>
        internal static string AlarmAreaSetFromCRFailed {
            get {
                return ResourceManager.GetString("AlarmAreaSetFromCRFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon tidsköp misslyckades.
        /// </summary>
        internal static string AlarmAreaTimeBuyingFailed {
            get {
                return ResourceManager.GetString("AlarmAreaTimeBuyingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla larmzon misslyckades..
        /// </summary>
        internal static string AlarmAreaUnsetFailed {
            get {
                return ResourceManager.GetString("AlarmAreaUnsetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockera.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockerad.
        /// </summary>
        internal static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockerad sektion ändrad.
        /// </summary>
        internal static string BlockedInputChanged {
            get {
                return ResourceManager.GetString("BlockedInputChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köpt tid.
        /// </summary>
        internal static string BoughtTime {
            get {
                return ResourceManager.GetString("BoughtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbrott.
        /// </summary>
        internal static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köp tid.
        /// </summary>
        internal static string BuyTime {
            get {
                return ResourceManager.GetString("BuyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kort.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dörrmiljö blockerad av licensrestriktion.
        /// </summary>
        internal static string DoorEnvironmentBlockedByLicence {
            get {
                return ResourceManager.GetString("DoorEnvironmentBlockedByLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Väntar.
        /// </summary>
        internal static string EISWaiting {
            get {
                return ResourceManager.GetString("EISWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkopplad.
        /// </summary>
        internal static string EventlogState_Set {
            get {
                return ResourceManager.GetString("EventlogState_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkopplad.
        /// </summary>
        internal static string EventlogState_Unset {
            get {
                return ResourceManager.GetString("EventlogState_Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon hittades inte..
        /// </summary>
        internal static string FailedAlarmAreaNotFound {
            get {
                return ResourceManager.GetString("FailedAlarmAreaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begärd tid är större än max tillåtet tidsköp per gång..
        /// </summary>
        internal static string FailedBoughtTimeDurationExceeded {
            get {
                return ResourceManager.GetString("FailedBoughtTimeDurationExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCU är offline..
        /// </summary>
        internal static string FailedCCUOffline {
            get {
                return ResourceManager.GetString("FailedCCUOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel..
        /// </summary>
        internal static string FailedDueError {
            get {
                return ResourceManager.GetString("FailedDueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektion larmar..
        /// </summary>
        internal static string FailedInputInAlarm {
            get {
                return ResourceManager.GetString("FailedInputInAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rättighet saknar..
        /// </summary>
        internal static string FailedInsufficientRights {
            get {
                return ResourceManager.GetString("FailedInsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köp tid har redan utförts..
        /// </summary>
        internal static string FailedTimeAlreadyBought {
            get {
                return ResourceManager.GetString("FailedTimeAlreadyBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köp tid är inte aktiverat..
        /// </summary>
        internal static string FailedTimeBuyingNotEnabled {
            get {
                return ResourceManager.GetString("FailedTimeBuyingNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid att köpa är noll..
        /// </summary>
        internal static string FailedTimeToBuyIsZero {
            get {
                return ResourceManager.GetString("FailedTimeToBuyIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begärd tid är större än max tillåtet tidsköp för larmzonen..
        /// </summary>
        internal static string FailedTotalBoughtTimeReached {
            get {
                return ResourceManager.GetString("FailedTotalBoughtTimeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektion status ändrad.
        /// </summary>
        internal static string InputStateChanged {
            get {
                return ResourceManager.GetString("InputStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrång.
        /// </summary>
        internal static string intrusion {
            get {
                return ResourceManager.GetString("intrusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senast köpta tid.
        /// </summary>
        internal static string lastBoughtTime {
            get {
                return ResourceManager.GetString("lastBoughtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blockerad.
        /// </summary>
        internal static string locked {
            get {
                return ResourceManager.GetString("locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera Larmzon.
        /// </summary>
        internal static string MENUACKNOWLEDGEAA {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGEAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera alla.
        /// </summary>
        internal static string MENUACKNOWLEDGEALL {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera&amp;perm.bl..
        /// </summary>
        internal static string MENUACKNOWLEDGEANDPERMANENTLYBLOCKSENSORALARM {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGEANDPERMANENTLYBLOCKSENSORALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera&amp;temp.bl..
        /// </summary>
        internal static string MENUACKNOWLEDGEANDTEMPORARILYBLOCKSENSORALARM {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGEANDTEMPORARILYBLOCKSENSORALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera sektion.
        /// </summary>
        internal static string MENUACKNOWLEDGESENSORALARM {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGESENSORALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera larm.
        /// </summary>
        internal static string MENUALALARMSTATEACKNOWLEDGE {
            get {
                return ResourceManager.GetString("MENUALALARMSTATEACKNOWLEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera&amp;block. larm.
        /// </summary>
        internal static string MENUALALARMSTATEACKNOWLEDGEANDBLOCK {
            get {
                return ResourceManager.GetString("MENUALALARMSTATEACKNOWLEDGEANDBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockera larm.
        /// </summary>
        internal static string MENUALALARMSTATEBLOCK {
            get {
                return ResourceManager.GetString("MENUALALARMSTATEBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla larmzon.
        /// </summary>
        internal static string MENUALALARMSTATEUNSETAA {
            get {
                return ResourceManager.GetString("MENUALALARMSTATEUNSETAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon redigera.
        /// </summary>
        internal static string MENUALARMAREAEDIT {
            get {
                return ResourceManager.GetString("MENUALARMAREAEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manöverpanel.
        /// </summary>
        internal static string MenuAlarmAreaPanel {
            get {
                return ResourceManager.GetString("MenuAlarmAreaPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzoner.
        /// </summary>
        internal static string MENUALARMAREAS {
            get {
                return ResourceManager.GetString("MENUALARMAREAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzoner GIN.
        /// </summary>
        internal static string MENUALARMAREASGIN {
            get {
                return ResourceManager.GetString("MENUALARMAREASGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon i larm.
        /// </summary>
        internal static string MENUALARMAREASINALARMSTATE {
            get {
                return ResourceManager.GetString("MENUALARMAREASINALARMSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon ej kvitterad.
        /// </summary>
        internal static string MENUALARMAREASNOTACKNOWLEDGED {
            get {
                return ResourceManager.GetString("MENUALARMAREASNOTACKNOWLEDGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzoner (+Kod).
        /// </summary>
        internal static string MENUALARMAREASPIN {
            get {
                return ResourceManager.GetString("MENUALARMAREASPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perm. blockering.
        /// </summary>
        internal static string MENUBLOCKSENSORPERMANENTLY {
            get {
                return ResourceManager.GetString("MENUBLOCKSENSORPERMANENTLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. blockering `29.
        /// </summary>
        internal static string MENUBLOCKSENSORTEMPORARILYAREAUNSET {
            get {
                return ResourceManager.GetString("MENUBLOCKSENSORTEMPORARILYAREAUNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. blockering `31.
        /// </summary>
        internal static string MENUBLOCKSENSORTEMPORARILYSENSORSTATENORMAL {
            get {
                return ResourceManager.GetString("MENUBLOCKSENSORTEMPORARILYSENSORSTATENORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akutkod.
        /// </summary>
        internal static string MENUEMERGENCYCODE {
            get {
                return ResourceManager.GetString("MENUEMERGENCYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redigera händelselogg.
        /// </summary>
        internal static string MENUEVENTLOGEDIT {
            get {
                return ResourceManager.GetString("MENUEVENTLOGEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen händelselogg.
        /// </summary>
        internal static string MENUEVENTLOGEMPTY {
            get {
                return ResourceManager.GetString("MENUEVENTLOGEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Händelselogg.
        /// </summary>
        internal static string MENUEVENTLOGS {
            get {
                return ResourceManager.GetString("MENUEVENTLOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera alla.
        /// </summary>
        internal static string MENUSENSORACKNOWLEDGEALL {
            get {
                return ResourceManager.GetString("MENUSENSORACKNOWLEDGEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvittera alla.
        /// </summary>
        internal static string MENUSENSORACKNOWLEDGEALLALARMAREAS {
            get {
                return ResourceManager.GetString("MENUSENSORACKNOWLEDGEALLALARMAREAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvitt. och block. alla.
        /// </summary>
        internal static string MENUSENSORACKNOWLEDGEANDBLOCKALL {
            get {
                return ResourceManager.GetString("MENUSENSORACKNOWLEDGEANDBLOCKALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockera alla(temp.bl.).
        /// </summary>
        internal static string MENUSENSORBLOCKALL {
            get {
                return ResourceManager.GetString("MENUSENSORBLOCKALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektion i larm.
        /// </summary>
        internal static string MENUSENSORINALARM {
            get {
                return ResourceManager.GetString("MENUSENSORINALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektion i sabotage.
        /// </summary>
        internal static string MENUSENSORINSABOTAGE {
            get {
                return ResourceManager.GetString("MENUSENSORINSABOTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektion ej kvitterad.
        /// </summary>
        internal static string MENUSENSORNOTACKNOWLEDGED {
            get {
                return ResourceManager.GetString("MENUSENSORNOTACKNOWLEDGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektion perm. blockerad.
        /// </summary>
        internal static string MENUSENSORPERMANENTLYBLOCKED {
            get {
                return ResourceManager.GetString("MENUSENSORPERMANENTLYBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektioner.
        /// </summary>
        internal static string MENUSENSORS {
            get {
                return ResourceManager.GetString("MENUSENSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektioner GIN.
        /// </summary>
        internal static string MENUSENSORSGIN {
            get {
                return ResourceManager.GetString("MENUSENSORSGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektioner i larm.
        /// </summary>
        internal static string MENUSENSORSINALARM {
            get {
                return ResourceManager.GetString("MENUSENSORSINALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S:er i sabotage.
        /// </summary>
        internal static string MENUSENSORSINSABOTAGE {
            get {
                return ResourceManager.GetString("MENUSENSORSINSABOTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S:er ej kvitterade.
        /// </summary>
        internal static string MENUSENSORSNOTACKNOWLEDGED {
            get {
                return ResourceManager.GetString("MENUSENSORSNOTACKNOWLEDGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S:er perm.block..
        /// </summary>
        internal static string MENUSENSORSPERMANENTLYBLOCKED {
            get {
                return ResourceManager.GetString("MENUSENSORSPERMANENTLYBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektioner (+Kod).
        /// </summary>
        internal static string MENUSENSORSPIN {
            get {
                return ResourceManager.GetString("MENUSENSORSPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S:er temp.block..
        /// </summary>
        internal static string MENUSENSORSTEMPORARILYBLOCKED {
            get {
                return ResourceManager.GetString("MENUSENSORSTEMPORARILYBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektion temp.block..
        /// </summary>
        internal static string MENUSENSORTEMPORARILYBLOCKED {
            get {
                return ResourceManager.GetString("MENUSENSORTEMPORARILYBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återinkoppla alla.
        /// </summary>
        internal static string MENUSENSORUNBLOCKALL {
            get {
                return ResourceManager.GetString("MENUSENSORUNBLOCKALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla.
        /// </summary>
        internal static string MENUSET {
            get {
                return ResourceManager.GetString("MENUSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla larmzon.
        /// </summary>
        internal static string MENUSETAA {
            get {
                return ResourceManager.GetString("MENUSETAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillk. utan förvarning.
        /// </summary>
        internal static string MENUSETAANOPREWARNING {
            get {
                return ResourceManager.GetString("MENUSETAANOPREWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla alla.
        /// </summary>
        internal static string MENUSETALL {
            get {
                return ResourceManager.GetString("MENUSETALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla händelseloggar.
        /// </summary>
        internal static string MENUSHOWEVENTLOGS {
            get {
                return ResourceManager.GetString("MENUSHOWEVENTLOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa sektioner.
        /// </summary>
        internal static string MENUSHOWSENSORS {
            get {
                return ResourceManager.GetString("MENUSHOWSENSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01:00.
        /// </summary>
        internal static string MENUTIMEBUYING1HOD {
            get {
                return ResourceManager.GetString("MENUTIMEBUYING1HOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:01.
        /// </summary>
        internal static string MENUTIMEBUYING1MIN {
            get {
                return ResourceManager.GetString("MENUTIMEBUYING1MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:30.
        /// </summary>
        internal static string MENUTIMEBUYING30MIN {
            get {
                return ResourceManager.GetString("MENUTIMEBUYING30MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. tid.
        /// </summary>
        internal static string MENUTIMEBUYINGMAX {
            get {
                return ResourceManager.GetString("MENUTIMEBUYINGMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppling.
        /// </summary>
        internal static string MENUTIMEBUYINGUNSET {
            get {
                return ResourceManager.GetString("MENUTIMEBUYINGUNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återinkoppla.
        /// </summary>
        internal static string MENUUNBLOCKINPUT {
            get {
                return ResourceManager.GetString("MENUUNBLOCKINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcerad tillkoppling.
        /// </summary>
        internal static string MENUUNCONDINTIONALSET {
            get {
                return ResourceManager.GetString("MENUUNCONDINTIONALSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla.
        /// </summary>
        internal static string MENUUNSET {
            get {
                return ResourceManager.GetString("MENUUNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla larmzon.
        /// </summary>
        internal static string MENUUNSETAA {
            get {
                return ResourceManager.GetString("MENUUNSETAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla alla.
        /// </summary>
        internal static string MENUUNSETALL {
            get {
                return ResourceManager.GetString("MENUUNSETALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla och kvittera.
        /// </summary>
        internal static string MENUUNSETANDACKNOWLEDGEAA {
            get {
                return ResourceManager.GetString("MENUUNSETANDACKNOWLEDGEAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknas.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga larmzoner att till/från-koppla.
        /// </summary>
        internal static string NoAAtoSetOrUnset {
            get {
                return ResourceManager.GetString("NoAAtoSetOrUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen åtgärd för aktuellt kort..
        /// </summary>
        internal static string NoActionForCurrentCard {
            get {
                return ResourceManager.GetString("NoActionForCurrentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns inga objekt att visa.
        /// </summary>
        internal static string NoItemsToDisplay {
            get {
                return ResourceManager.GetString("NoItemsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externt system bekräftade inte till/från-koppling.
        /// </summary>
        internal static string NotConfirmSetUnsetAAFromEIS {
            get {
                return ResourceManager.GetString("NotConfirmSetUnsetAAFromEIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekt:.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekt typ.
        /// </summary>
        internal static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Från.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utför åtgärd?.
        /// </summary>
        internal static string PerformAction {
            get {
                return ResourceManager.GetString("PerformAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utfört av:.
        /// </summary>
        internal static string PerformedBy {
            get {
                return ResourceManager.GetString("PerformedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förvarning.
        /// </summary>
        internal static string Prewarning {
            get {
                return ResourceManager.GetString("Prewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återstående tid.
        /// </summary>
        internal static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återstående.
        /// </summary>
        internal static string Remining {
            get {
                return ResourceManager.GetString("Remining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabotage.
        /// </summary>
        internal static string sabotage {
            get {
                return ResourceManager.GetString("sabotage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Klient för mer info.
        /// </summary>
        internal static string SeeClientForMoreInfo {
            get {
                return ResourceManager.GetString("SeeClientForMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla larmzon misslyckades.
        /// </summary>
        internal static string SetAAfailed {
            get {
                return ResourceManager.GetString("SetAAfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla larmzon lyckades.
        /// </summary>
        internal static string SetAAsucceeded {
            get {
                return ResourceManager.GetString("SetAAsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon tillkopplad med objekt för automatisk tillkoppling.
        /// </summary>
        internal static string SetAlarmAreaByObjectForAutomaticActivation {
            get {
                return ResourceManager.GetString("SetAlarmAreaByObjectForAutomaticActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla larmzon.
        /// </summary>
        internal static string SetAlarmAreaFromCardReader {
            get {
                return ResourceManager.GetString("SetAlarmAreaFromCardReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon tillkopplad från klient.
        /// </summary>
        internal static string SetAlarmAreaFromClient {
            get {
                return ResourceManager.GetString("SetAlarmAreaFromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla larmzoner misslyckades. Tillkopplade larmzoner: {0}.
        /// </summary>
        internal static string SetFailure {
            get {
                return ResourceManager.GetString("SetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillkoppla larmzoner lyckades.
        /// </summary>
        internal static string SetSuccess {
            get {
                return ResourceManager.GetString("SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kortslutning.
        /// </summary>
        internal static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabotage.
        /// </summary>
        internal static string Tamper {
            get {
                return ResourceManager.GetString("Tamper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporärt blockerad sektion ändrad.
        /// </summary>
        internal static string TemporarilyBlockedInputChanged {
            get {
                return ResourceManager.GetString("TemporarilyBlockedInputChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köp tid misslyckades. Anledning:.
        /// </summary>
        internal static string TimeBuyingFailed {
            get {
                return ResourceManager.GetString("TimeBuyingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissa larmzoner kräver tidsköp.
        /// </summary>
        internal static string TimeBuyingRequired {
            get {
                return ResourceManager.GetString("TimeBuyingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köp tid lyckades..
        /// </summary>
        internal static string TimeBuyingSucceeded {
            get {
                return ResourceManager.GetString("TimeBuyingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid att köpa.
        /// </summary>
        internal static string TimeToBuy {
            get {
                return ResourceManager.GetString("TimeToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tid köpt.
        /// </summary>
        internal static string totalBoughtTime {
            get {
                return ResourceManager.GetString("totalBoughtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återinkopplad.
        /// </summary>
        internal static string Unblocked {
            get {
                return ResourceManager.GetString("Unblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcerad tillkoppling misslyckades.
        /// </summary>
        internal static string UnconditionalSetAAfailed {
            get {
                return ResourceManager.GetString("UnconditionalSetAAfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcerad tillkoppling lyckades.
        /// </summary>
        internal static string UnconditionalSetAAsucceeded {
            get {
                return ResourceManager.GetString("UnconditionalSetAAsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcerad tillkoppling.
        /// </summary>
        internal static string UnconditionaSet {
            get {
                return ResourceManager.GetString("UnconditionaSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okänd.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obegränsad.
        /// </summary>
        internal static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to återinkopplad.
        /// </summary>
        internal static string unlocked {
            get {
                return ResourceManager.GetString("unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla.
        /// </summary>
        internal static string Unset {
            get {
                return ResourceManager.GetString("Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla larmzon misslyckades.
        /// </summary>
        internal static string UnsetAAfailed {
            get {
                return ResourceManager.GetString("UnsetAAfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla larmzon lyckades.
        /// </summary>
        internal static string UnsetAAsucceeded {
            get {
                return ResourceManager.GetString("UnsetAAsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larmzon frånkopplad med objekt för automatisk tillkoppling.
        /// </summary>
        internal static string UnsetAlarmAreaByObjectForAutomaticActivation {
            get {
                return ResourceManager.GetString("UnsetAlarmAreaByObjectForAutomaticActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla larmzon med kortläsare.
        /// </summary>
        internal static string UnsetAlarmAreaFromCardReader {
            get {
                return ResourceManager.GetString("UnsetAlarmAreaFromCardReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla larmzon från klient.
        /// </summary>
        internal static string UnsetAlarmAreaFromClient {
            get {
                return ResourceManager.GetString("UnsetAlarmAreaFromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla larmzoner misslyckades. Frånkopplade larmzoner: {0}.
        /// </summary>
        internal static string UnsetFailure {
            get {
                return ResourceManager.GetString("UnsetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkoppla larmzoner lyckades.
        /// </summary>
        internal static string UnsetSuccess {
            get {
                return ResourceManager.GetString("UnsetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Använd tid.
        /// </summary>
        internal static string UsedTime {
            get {
                return ResourceManager.GetString("UsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Väntar på externt system.
        /// </summary>
        internal static string WaitingForEIS {
            get {
                return ResourceManager.GetString("WaitingForEIS", resourceCulture);
            }
        }
    }
}
