//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.NCAS.CCU.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Localization_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Localization_English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.NCAS.CCU.Localization.Localization.English", typeof(Localization_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA cannot be set some sensors are active.
        /// </summary>
        internal static string AAcannotBeSet {
            get {
                return ResourceManager.GetString("AAcannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        internal static string Acknowledge {
            get {
                return ResourceManager.GetString("Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge and block.
        /// </summary>
        internal static string AcknowledgeAndBlock {
            get {
                return ResourceManager.GetString("AcknowledgeAndBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        internal static string Acknowledged {
            get {
                return ResourceManager.GetString("Acknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge input alarm.
        /// </summary>
        internal static string AcknowledgeInputAlarm {
            get {
                return ResourceManager.GetString("AcknowledgeInputAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm area.
        /// </summary>
        internal static string AlarmArea {
            get {
                return ResourceManager.GetString("AlarmArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm area state changed alarm.
        /// </summary>
        internal static string AlarmAreaAlarmStateChangeAlarm {
            get {
                return ResourceManager.GetString("AlarmAreaAlarmStateChangeAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Area alarm state changed.
        /// </summary>
        internal static string AlarmAreaAlarmStateChanged {
            get {
                return ResourceManager.GetString("AlarmAreaAlarmStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm area bought time changed.
        /// </summary>
        internal static string AlarmAreaBoughtTimeChanged {
            get {
                return ResourceManager.GetString("AlarmAreaBoughtTimeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm area bought time expired.
        /// </summary>
        internal static string AlarmAreaBoughtTimeExpired {
            get {
                return ResourceManager.GetString("AlarmAreaBoughtTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alam area cannot be set, some sensors are in alarm state.
        /// </summary>
        internal static string AlarmAreaCanNotBeSet {
            get {
                return ResourceManager.GetString("AlarmAreaCanNotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Area has been in alarm state during set period..
        /// </summary>
        internal static string AlarmAreaHasBeenInAlarmStateDuringSetPeriod {
            get {
                return ResourceManager.GetString("AlarmAreaHasBeenInAlarmStateDuringSetPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm area sabotage state changed.
        /// </summary>
        internal static string AlarmAreaSabotageStateChanged {
            get {
                return ResourceManager.GetString("AlarmAreaSabotageStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor alarm acknowledged.
        /// </summary>
        internal static string AlarmAreaSensorAlarmAcknowledged {
            get {
                return ResourceManager.GetString("AlarmAreaSensorAlarmAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor blocking type changed.
        /// </summary>
        internal static string AlarmAreaSensorBlockingTypeChanged {
            get {
                return ResourceManager.GetString("AlarmAreaSensorBlockingTypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor state changed.
        /// </summary>
        internal static string AlarmAreaSensorStateChangedOnlyForCardReader {
            get {
                return ResourceManager.GetString("AlarmAreaSensorStateChangedOnlyForCardReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm area set from CR failed.
        /// </summary>
        internal static string AlarmAreaSetFromCRFailed {
            get {
                return ResourceManager.GetString("AlarmAreaSetFromCRFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm area time buying failed.
        /// </summary>
        internal static string AlarmAreaTimeBuyingFailed {
            get {
                return ResourceManager.GetString("AlarmAreaTimeBuyingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked input changed.
        /// </summary>
        internal static string BlockedInputChanged {
            get {
                return ResourceManager.GetString("BlockedInputChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bought time.
        /// </summary>
        internal static string BoughtTime {
            get {
                return ResourceManager.GetString("BoughtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        internal static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyTime.
        /// </summary>
        internal static string BuyTime {
            get {
                return ResourceManager.GetString("BuyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door environment blocked by licence.
        /// </summary>
        internal static string DoorEnvironmentBlockedByLicence {
            get {
                return ResourceManager.GetString("DoorEnvironmentBlockedByLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIS-Waiting.
        /// </summary>
        internal static string EISWaiting {
            get {
                return ResourceManager.GetString("EISWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string EventlogState_Set {
            get {
                return ResourceManager.GetString("EventlogState_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        internal static string EventlogState_Unset {
            get {
                return ResourceManager.GetString("EventlogState_Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm area was not found..
        /// </summary>
        internal static string FailedAlarmAreaNotFound {
            get {
                return ResourceManager.GetString("FailedAlarmAreaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested time to buy is bigger than one time limit..
        /// </summary>
        internal static string FailedBoughtTimeDurationExceeded {
            get {
                return ResourceManager.GetString("FailedBoughtTimeDurationExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCU is offline..
        /// </summary>
        internal static string FailedCCUOffline {
            get {
                return ResourceManager.GetString("FailedCCUOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        internal static string FailedDueError {
            get {
                return ResourceManager.GetString("FailedDueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is in alarm state..
        /// </summary>
        internal static string FailedInputInAlarm {
            get {
                return ResourceManager.GetString("FailedInputInAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient rights..
        /// </summary>
        internal static string FailedInsufficientRights {
            get {
                return ResourceManager.GetString("FailedInsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time was already bought..
        /// </summary>
        internal static string FailedTimeAlreadyBought {
            get {
                return ResourceManager.GetString("FailedTimeAlreadyBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time buying is not enabled..
        /// </summary>
        internal static string FailedTimeBuyingNotEnabled {
            get {
                return ResourceManager.GetString("FailedTimeBuyingNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to buy is zero..
        /// </summary>
        internal static string FailedTimeToBuyIsZero {
            get {
                return ResourceManager.GetString("FailedTimeToBuyIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested time to buy is bigger than limit for AA..
        /// </summary>
        internal static string FailedTotalBoughtTimeReached {
            get {
                return ResourceManager.GetString("FailedTotalBoughtTimeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input state changed.
        /// </summary>
        internal static string InputStateChanged {
            get {
                return ResourceManager.GetString("InputStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrusion.
        /// </summary>
        internal static string intrusion {
            get {
                return ResourceManager.GetString("intrusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last bought time.
        /// </summary>
        internal static string lastBoughtTime {
            get {
                return ResourceManager.GetString("lastBoughtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locked.
        /// </summary>
        internal static string locked {
            get {
                return ResourceManager.GetString("locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge AA.
        /// </summary>
        internal static string MENUACKNOWLEDGEAA {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGEAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge all.
        /// </summary>
        internal static string MENUACKNOWLEDGEALL {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack. and perm. block.
        /// </summary>
        internal static string MENUACKNOWLEDGEANDPERMANENTLYBLOCKSENSORALARM {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGEANDPERMANENTLYBLOCKSENSORALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack. and temp. block.
        /// </summary>
        internal static string MENUACKNOWLEDGEANDTEMPORARILYBLOCKSENSORALARM {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGEANDTEMPORARILYBLOCKSENSORALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        internal static string MENUACKNOWLEDGESENSORALARM {
            get {
                return ResourceManager.GetString("MENUACKNOWLEDGESENSORALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge alarm.
        /// </summary>
        internal static string MENUALALARMSTATEACKNOWLEDGE {
            get {
                return ResourceManager.GetString("MENUALALARMSTATEACKNOWLEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack. and block alarm.
        /// </summary>
        internal static string MENUALALARMSTATEACKNOWLEDGEANDBLOCK {
            get {
                return ResourceManager.GetString("MENUALALARMSTATEACKNOWLEDGEANDBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block alarm.
        /// </summary>
        internal static string MENUALALARMSTATEBLOCK {
            get {
                return ResourceManager.GetString("MENUALALARMSTATEBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset AA.
        /// </summary>
        internal static string MENUALALARMSTATEUNSETAA {
            get {
                return ResourceManager.GetString("MENUALALARMSTATEUNSETAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm area edit.
        /// </summary>
        internal static string MENUALARMAREAEDIT {
            get {
                return ResourceManager.GetString("MENUALARMAREAEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm panel.
        /// </summary>
        internal static string MenuAlarmAreaPanel {
            get {
                return ResourceManager.GetString("MenuAlarmAreaPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm areas.
        /// </summary>
        internal static string MENUALARMAREAS {
            get {
                return ResourceManager.GetString("MENUALARMAREAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm areas GIN.
        /// </summary>
        internal static string MENUALARMAREASGIN {
            get {
                return ResourceManager.GetString("MENUALARMAREASGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA in alarm state.
        /// </summary>
        internal static string MENUALARMAREASINALARMSTATE {
            get {
                return ResourceManager.GetString("MENUALARMAREASINALARMSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA not acknowledged.
        /// </summary>
        internal static string MENUALARMAREASNOTACKNOWLEDGED {
            get {
                return ResourceManager.GetString("MENUALARMAREASNOTACKNOWLEDGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm areas (+PIN).
        /// </summary>
        internal static string MENUALARMAREASPIN {
            get {
                return ResourceManager.GetString("MENUALARMAREASPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently block.
        /// </summary>
        internal static string MENUBLOCKSENSORPERMANENTLY {
            get {
                return ResourceManager.GetString("MENUBLOCKSENSORPERMANENTLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily block `29.
        /// </summary>
        internal static string MENUBLOCKSENSORTEMPORARILYAREAUNSET {
            get {
                return ResourceManager.GetString("MENUBLOCKSENSORTEMPORARILYAREAUNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily block `31.
        /// </summary>
        internal static string MENUBLOCKSENSORTEMPORARILYSENSORSTATENORMAL {
            get {
                return ResourceManager.GetString("MENUBLOCKSENSORTEMPORARILYSENSORSTATENORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        internal static string MENUEMERGENCYCODE {
            get {
                return ResourceManager.GetString("MENUEMERGENCYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event log edit.
        /// </summary>
        internal static string MENUEVENTLOGEDIT {
            get {
                return ResourceManager.GetString("MENUEVENTLOGEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events.
        /// </summary>
        internal static string MENUEVENTLOGEMPTY {
            get {
                return ResourceManager.GetString("MENUEVENTLOGEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventlog.
        /// </summary>
        internal static string MENUEVENTLOGS {
            get {
                return ResourceManager.GetString("MENUEVENTLOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge all.
        /// </summary>
        internal static string MENUSENSORACKNOWLEDGEALL {
            get {
                return ResourceManager.GetString("MENUSENSORACKNOWLEDGEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge all.
        /// </summary>
        internal static string MENUSENSORACKNOWLEDGEALLALARMAREAS {
            get {
                return ResourceManager.GetString("MENUSENSORACKNOWLEDGEALLALARMAREAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge and block all.
        /// </summary>
        internal static string MENUSENSORACKNOWLEDGEANDBLOCKALL {
            get {
                return ResourceManager.GetString("MENUSENSORACKNOWLEDGEANDBLOCKALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block all(temp.block).
        /// </summary>
        internal static string MENUSENSORBLOCKALL {
            get {
                return ResourceManager.GetString("MENUSENSORBLOCKALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor in alarm.
        /// </summary>
        internal static string MENUSENSORINALARM {
            get {
                return ResourceManager.GetString("MENUSENSORINALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor in sabotage.
        /// </summary>
        internal static string MENUSENSORINSABOTAGE {
            get {
                return ResourceManager.GetString("MENUSENSORINSABOTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor not acknowledged.
        /// </summary>
        internal static string MENUSENSORNOTACKNOWLEDGED {
            get {
                return ResourceManager.GetString("MENUSENSORNOTACKNOWLEDGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor perm. blocked.
        /// </summary>
        internal static string MENUSENSORPERMANENTLYBLOCKED {
            get {
                return ResourceManager.GetString("MENUSENSORPERMANENTLYBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        internal static string MENUSENSORS {
            get {
                return ResourceManager.GetString("MENUSENSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors GIN.
        /// </summary>
        internal static string MENUSENSORSGIN {
            get {
                return ResourceManager.GetString("MENUSENSORSGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors in alarm.
        /// </summary>
        internal static string MENUSENSORSINALARM {
            get {
                return ResourceManager.GetString("MENUSENSORSINALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors in sabotage.
        /// </summary>
        internal static string MENUSENSORSINSABOTAGE {
            get {
                return ResourceManager.GetString("MENUSENSORSINSABOTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors not acknowledged.
        /// </summary>
        internal static string MENUSENSORSNOTACKNOWLEDGED {
            get {
                return ResourceManager.GetString("MENUSENSORSNOTACKNOWLEDGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors perm. blocked.
        /// </summary>
        internal static string MENUSENSORSPERMANENTLYBLOCKED {
            get {
                return ResourceManager.GetString("MENUSENSORSPERMANENTLYBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors (+PIN).
        /// </summary>
        internal static string MENUSENSORSPIN {
            get {
                return ResourceManager.GetString("MENUSENSORSPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors temp. blocked.
        /// </summary>
        internal static string MENUSENSORSTEMPORARILYBLOCKED {
            get {
                return ResourceManager.GetString("MENUSENSORSTEMPORARILYBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor temp. blocked.
        /// </summary>
        internal static string MENUSENSORTEMPORARILYBLOCKED {
            get {
                return ResourceManager.GetString("MENUSENSORTEMPORARILYBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock all.
        /// </summary>
        internal static string MENUSENSORUNBLOCKALL {
            get {
                return ResourceManager.GetString("MENUSENSORUNBLOCKALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string MENUSET {
            get {
                return ResourceManager.GetString("MENUSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set AA.
        /// </summary>
        internal static string MENUSETAA {
            get {
                return ResourceManager.GetString("MENUSETAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set AA w/o prewarning.
        /// </summary>
        internal static string MENUSETAANOPREWARNING {
            get {
                return ResourceManager.GetString("MENUSETAANOPREWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set all.
        /// </summary>
        internal static string MENUSETALL {
            get {
                return ResourceManager.GetString("MENUSETALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all eventlogs.
        /// </summary>
        internal static string MENUSHOWEVENTLOGS {
            get {
                return ResourceManager.GetString("MENUSHOWEVENTLOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sensors.
        /// </summary>
        internal static string MENUSHOWSENSORS {
            get {
                return ResourceManager.GetString("MENUSHOWSENSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01:00.
        /// </summary>
        internal static string MENUTIMEBUYING1HOD {
            get {
                return ResourceManager.GetString("MENUTIMEBUYING1HOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:01.
        /// </summary>
        internal static string MENUTIMEBUYING1MIN {
            get {
                return ResourceManager.GetString("MENUTIMEBUYING1MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:30.
        /// </summary>
        internal static string MENUTIMEBUYING30MIN {
            get {
                return ResourceManager.GetString("MENUTIMEBUYING30MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max. time.
        /// </summary>
        internal static string MENUTIMEBUYINGMAX {
            get {
                return ResourceManager.GetString("MENUTIMEBUYINGMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        internal static string MENUTIMEBUYINGUNSET {
            get {
                return ResourceManager.GetString("MENUTIMEBUYINGUNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        internal static string MENUUNBLOCKINPUT {
            get {
                return ResourceManager.GetString("MENUUNBLOCKINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncodintional set AA.
        /// </summary>
        internal static string MENUUNCONDINTIONALSET {
            get {
                return ResourceManager.GetString("MENUUNCONDINTIONALSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        internal static string MENUUNSET {
            get {
                return ResourceManager.GetString("MENUUNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset AA.
        /// </summary>
        internal static string MENUUNSETAA {
            get {
                return ResourceManager.GetString("MENUUNSETAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset all.
        /// </summary>
        internal static string MENUUNSETALL {
            get {
                return ResourceManager.GetString("MENUUNSETALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset and acknowledge AA.
        /// </summary>
        internal static string MENUUNSETANDACKNOWLEDGEAA {
            get {
                return ResourceManager.GetString("MENUUNSETANDACKNOWLEDGEAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing time.
        /// </summary>
        internal static string MissingTime {
            get {
                return ResourceManager.GetString("MissingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No alarm areas to set or unset..
        /// </summary>
        internal static string NoAAtoSetOrUnset {
            get {
                return ResourceManager.GetString("NoAAtoSetOrUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action for current card..
        /// </summary>
        internal static string NoActionForCurrentCard {
            get {
                return ResourceManager.GetString("NoActionForCurrentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no alarm areas to display in this menu.
        /// </summary>
        internal static string NoAlarmAreasToDisplay {
            get {
                return ResourceManager.GetString("NoAlarmAreasToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no alarm areas with eventlogs to be displayed.
        /// </summary>
        internal static string NoAlarmAreasWithEventlogsToDisplay {
            get {
                return ResourceManager.GetString("NoAlarmAreasWithEventlogsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events to display for this alarm area.
        /// </summary>
        internal static string NoEventsToDisplay {
            get {
                return ResourceManager.GetString("NoEventsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to display.
        /// </summary>
        internal static string NoItemsToDisplay {
            get {
                return ResourceManager.GetString("NoItemsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not confirm set/unset alarm area from EIS.
        /// </summary>
        internal static string NotConfirmSetUnsetAAFromEIS {
            get {
                return ResourceManager.GetString("NotConfirmSetUnsetAAFromEIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object: .
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type.
        /// </summary>
        internal static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily plan.
        /// </summary>
        internal static string ObjectType_DailyPlan {
            get {
                return ResourceManager.GetString("ObjectType_DailyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string ObjectType_Input {
            get {
                return ResourceManager.GetString("ObjectType_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string ObjectType_Output {
            get {
                return ResourceManager.GetString("ObjectType_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        internal static string ObjectType_TimeZone {
            get {
                return ResourceManager.GetString("ObjectType_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform an action?.
        /// </summary>
        internal static string PerformAction {
            get {
                return ResourceManager.GetString("PerformAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performed by.
        /// </summary>
        internal static string PerformedBy {
            get {
                return ResourceManager.GetString("PerformedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prewarning.
        /// </summary>
        internal static string Prewarning {
            get {
                return ResourceManager.GetString("Prewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are actions bound to this inputs&apos;s state. They will be executed after the input is unblocked. Do you want to proceed with unblocking?.
        /// </summary>
        internal static string QuestionDoYouWantToProceedWithUnblockingInput {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToProceedWithUnblockingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are actions bound to state of some inputs. They will be executed after the inputs are unblocked. Do you want to proceed with unblocking?.
        /// </summary>
        internal static string QuestionDoYouWantToProceedWithUnblockingInputs {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToProceedWithUnblockingInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time.
        /// </summary>
        internal static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remining.
        /// </summary>
        internal static string Remining {
            get {
                return ResourceManager.GetString("Remining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabotage.
        /// </summary>
        internal static string sabotage {
            get {
                return ResourceManager.GetString("sabotage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Client for more info.
        /// </summary>
        internal static string SeeClientForMoreInfo {
            get {
                return ResourceManager.GetString("SeeClientForMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set alarm area failed.
        /// </summary>
        internal static string SetAAfailed {
            get {
                return ResourceManager.GetString("SetAAfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set alarm area succeeded.
        /// </summary>
        internal static string SetAAsucceeded {
            get {
                return ResourceManager.GetString("SetAAsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set alarm area by object for automatic activation.
        /// </summary>
        internal static string SetAlarmAreaByObjectForAutomaticActivation {
            get {
                return ResourceManager.GetString("SetAlarmAreaByObjectForAutomaticActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set alarm area.
        /// </summary>
        internal static string SetAlarmAreaFromCardReader {
            get {
                return ResourceManager.GetString("SetAlarmAreaFromCardReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set alarm area from client.
        /// </summary>
        internal static string SetAlarmAreaFromClient {
            get {
                return ResourceManager.GetString("SetAlarmAreaFromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set alarm areas failed. Set alarm areas: {0}.
        /// </summary>
        internal static string SetFailure {
            get {
                return ResourceManager.GetString("SetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set alarm areas succeeded.
        /// </summary>
        internal static string SetSuccess {
            get {
                return ResourceManager.GetString("SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamper.
        /// </summary>
        internal static string Tamper {
            get {
                return ResourceManager.GetString("Tamper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily blocked input changed.
        /// </summary>
        internal static string TemporarilyBlockedInputChanged {
            get {
                return ResourceManager.GetString("TemporarilyBlockedInputChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time buying failed for some alarm areas..
        /// </summary>
        internal static string TimeBuyingErrors {
            get {
                return ResourceManager.GetString("TimeBuyingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time buying failed.  Reason:.
        /// </summary>
        internal static string TimeBuyingFailed {
            get {
                return ResourceManager.GetString("TimeBuyingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some alarm areas require time buying..
        /// </summary>
        internal static string TimeBuyingRequired {
            get {
                return ResourceManager.GetString("TimeBuyingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time buying succeeded..
        /// </summary>
        internal static string TimeBuyingSucceeded {
            get {
                return ResourceManager.GetString("TimeBuyingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to buy.
        /// </summary>
        internal static string TimeToBuy {
            get {
                return ResourceManager.GetString("TimeToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total bought time.
        /// </summary>
        internal static string totalBoughtTime {
            get {
                return ResourceManager.GetString("totalBoughtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: .
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblocked.
        /// </summary>
        internal static string Unblocked {
            get {
                return ResourceManager.GetString("Unblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unc. set alarm area failed.
        /// </summary>
        internal static string UnconditionalSetAAfailed {
            get {
                return ResourceManager.GetString("UnconditionalSetAAfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unc. set alarm area succeeded.
        /// </summary>
        internal static string UnconditionalSetAAsucceeded {
            get {
                return ResourceManager.GetString("UnconditionalSetAAsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconditiona set.
        /// </summary>
        internal static string UnconditionaSet {
            get {
                return ResourceManager.GetString("UnconditionaSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlocked.
        /// </summary>
        internal static string unlocked {
            get {
                return ResourceManager.GetString("unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        internal static string Unset {
            get {
                return ResourceManager.GetString("Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset alarm area failed.
        /// </summary>
        internal static string UnsetAAfailed {
            get {
                return ResourceManager.GetString("UnsetAAfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset alarm area succeeded.
        /// </summary>
        internal static string UnsetAAsucceeded {
            get {
                return ResourceManager.GetString("UnsetAAsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset alarm area by object for automatic activation.
        /// </summary>
        internal static string UnsetAlarmAreaByObjectForAutomaticActivation {
            get {
                return ResourceManager.GetString("UnsetAlarmAreaByObjectForAutomaticActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset alarm area from card reader.
        /// </summary>
        internal static string UnsetAlarmAreaFromCardReader {
            get {
                return ResourceManager.GetString("UnsetAlarmAreaFromCardReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset alarm area from client.
        /// </summary>
        internal static string UnsetAlarmAreaFromClient {
            get {
                return ResourceManager.GetString("UnsetAlarmAreaFromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset for some alarm areas failed. Unset alarm areas: {0}.
        /// </summary>
        internal static string UnsetFailure {
            get {
                return ResourceManager.GetString("UnsetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} more. Press &apos;Yes&apos; to see them all.
        /// </summary>
        internal static string UnsetNotAcknowledgedInSetPeriodAll {
            get {
                return ResourceManager.GetString("UnsetNotAcknowledgedInSetPeriodAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAs with nonack. alarm during set period:.
        /// </summary>
        internal static string UnsetNotAcknowledgedInSetPeriodList {
            get {
                return ResourceManager.GetString("UnsetNotAcknowledgedInSetPeriodList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset alarm areas succeeded.
        /// </summary>
        internal static string UnsetSuccess {
            get {
                return ResourceManager.GetString("UnsetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used time.
        /// </summary>
        internal static string UsedTime {
            get {
                return ResourceManager.GetString("UsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for EIS.
        /// </summary>
        internal static string WaitingForEIS {
            get {
                return ResourceManager.GetString("WaitingForEIS", resourceCulture);
            }
        }
    }
}
