//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.NCAS.CCU.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Localization_Slovak {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Localization_Slovak() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.NCAS.CCU.Localization.Localization.Slovak", typeof(Localization_Slovak).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZ nemôže byť zasetovaná, niektoré senzory sú aktívne..
        /// </summary>
        internal static string AAcannotBeSet {
            get {
                return ResourceManager.GetString("AAcannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarmová zóna bola v alarmovom stave počas aktivácie..
        /// </summary>
        internal static string AlarmAreaHasBeenInAlarmStateDuringSetPeriod {
            get {
                return ResourceManager.GetString("AlarmAreaHasBeenInAlarmStateDuringSetPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivovanie a. zóny zlyhalo..
        /// </summary>
        internal static string AlarmAreaSetFailed {
            get {
                return ResourceManager.GetString("AlarmAreaSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivovanie a.zóny zlyhalo..
        /// </summary>
        internal static string AlarmAreaUnsetFailed {
            get {
                return ResourceManager.GetString("AlarmAreaUnsetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kúpený.
        /// </summary>
        internal static string Bought {
            get {
                return ResourceManager.GetString("Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kúpený čas.
        /// </summary>
        internal static string BoughtTime {
            get {
                return ResourceManager.GetString("BoughtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dverné prostredie blokované licenciou.
        /// </summary>
        internal static string DoorEnvironmentBlockedByLicence {
            get {
                return ResourceManager.GetString("DoorEnvironmentBlockedByLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIS-Čaká sa.
        /// </summary>
        internal static string EISWaiting {
            get {
                return ResourceManager.GetString("EISWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarmová zóna sa nenašla..
        /// </summary>
        internal static string FailedAlarmAreaNotFound {
            get {
                return ResourceManager.GetString("FailedAlarmAreaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakup. čas prekročil limit jedného nákupu..
        /// </summary>
        internal static string FailedBoughtTimeDurationExceeded {
            get {
                return ResourceManager.GetString("FailedBoughtTimeDurationExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCU je offline..
        /// </summary>
        internal static string FailedCCUOffline {
            get {
                return ResourceManager.GetString("FailedCCUOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba..
        /// </summary>
        internal static string FailedDueError {
            get {
                return ResourceManager.GetString("FailedDueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vstup je v alarm stave..
        /// </summary>
        internal static string FailedInputInAlarm {
            get {
                return ResourceManager.GetString("FailedInputInAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedostatočné oprávnenie..
        /// </summary>
        internal static string FailedInsufficientRights {
            get {
                return ResourceManager.GetString("FailedInsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas bol už nakúpený..
        /// </summary>
        internal static string FailedTimeAlreadyBought {
            get {
                return ResourceManager.GetString("FailedTimeAlreadyBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakupovanie času nie je zapnuté..
        /// </summary>
        internal static string FailedTimeBuyingNotEnabled {
            get {
                return ResourceManager.GetString("FailedTimeBuyingNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakupovaný čas je nula..
        /// </summary>
        internal static string FailedTimeToBuyIsZero {
            get {
                return ResourceManager.GetString("FailedTimeToBuyIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakup. čas prekročil celkový limit a.zóny..
        /// </summary>
        internal static string FailedTotalBoughtTimeReached {
            get {
                return ResourceManager.GetString("FailedTotalBoughtTimeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm panel.
        /// </summary>
        internal static string MenuAlarmAreaPanel {
            get {
                return ResourceManager.GetString("MenuAlarmAreaPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kúpiť čas 01:00.
        /// </summary>
        internal static string MENUTIMEBUYING1HOD {
            get {
                return ResourceManager.GetString("MENUTIMEBUYING1HOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kúpiť čas 00:01.
        /// </summary>
        internal static string MENUTIMEBUYING1MIN {
            get {
                return ResourceManager.GetString("MENUTIMEBUYING1MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kúpiť čas 00:30.
        /// </summary>
        internal static string MENUTIMEBUYING30MIN {
            get {
                return ResourceManager.GetString("MENUTIMEBUYING30MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivovanie.
        /// </summary>
        internal static string MENUTIMEBUYINGUNSET {
            get {
                return ResourceManager.GetString("MENUTIMEBUYINGUNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chýba.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chýbajúci čas.
        /// </summary>
        internal static string MissingTime {
            get {
                return ResourceManager.GetString("MissingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žiadne a. zóny pre aktivovanie alebo deaktivovanie.
        /// </summary>
        internal static string NoAAtoSetOrUnset {
            get {
                return ResourceManager.GetString("NoAAtoSetOrUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žiadna akcia pre aktuálnu kartu..
        /// </summary>
        internal static string NoActionForCurrentCard {
            get {
                return ResourceManager.GetString("NoActionForCurrentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vykonať akciu?.
        /// </summary>
        internal static string PerformAction {
            get {
                return ResourceManager.GetString("PerformAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na stav tohto vstupu sú naviazané ďalšie akcie, ktoré budú v dôsledku jeho odblokovania vykonané. Chcete vstup napriek tomu odblokovať?.
        /// </summary>
        internal static string QuestionDoYouWantToProceedWithUnblockingInput {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToProceedWithUnblockingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na stav niektorých vstupov sú naviazané ďalšie akcie, ktoré budú v dôsledku ich odblokovania vykonané. Chcete vstupy napriek tomu odblokovať?.
        /// </summary>
        internal static string QuestionDoYouWantToProceedWithUnblockingInputs {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToProceedWithUnblockingInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostávajúci čas.
        /// </summary>
        internal static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostáva.
        /// </summary>
        internal static string Remining {
            get {
                return ResourceManager.GetString("Remining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivovanie a. zóny zlyhalo.
        /// </summary>
        internal static string SetAAfailed {
            get {
                return ResourceManager.GetString("SetAAfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivovanie a. zóny prebehlo úspešne.
        /// </summary>
        internal static string SetAAsucceeded {
            get {
                return ResourceManager.GetString("SetAAsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivovanie a. zón zlyhalo. Aktivované a. zóny: {0}.
        /// </summary>
        internal static string SetFailure {
            get {
                return ResourceManager.GetString("SetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivovanie a. zón prebehlo úspešne.
        /// </summary>
        internal static string SetSuccess {
            get {
                return ResourceManager.GetString("SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakupovanie času pre niektoré alarmové zóny zlyhalo..
        /// </summary>
        internal static string TimeBuyingErrors {
            get {
                return ResourceManager.GetString("TimeBuyingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakupovanie času zlyhalo. Dôvod:.
        /// </summary>
        internal static string TimeBuyingFailed {
            get {
                return ResourceManager.GetString("TimeBuyingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niektoré alarm. zóny vyžadujú nákup času..
        /// </summary>
        internal static string TimeBuyingRequired {
            get {
                return ResourceManager.GetString("TimeBuyingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakupovanie času bolo úspešné..
        /// </summary>
        internal static string TimeBuyingSucceeded {
            get {
                return ResourceManager.GetString("TimeBuyingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpod. aktivovanie a. zóny zlyhalo.
        /// </summary>
        internal static string UnconditionalSetAAfailed {
            get {
                return ResourceManager.GetString("UnconditionalSetAAfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpod. aktivovanie a. zóny bolo úspešne.
        /// </summary>
        internal static string UnconditionalSetAAsucceeded {
            get {
                return ResourceManager.GetString("UnconditionalSetAAsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEZNÁMY.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neobmedzený.
        /// </summary>
        internal static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivovanie a.zóny zlyhalo..
        /// </summary>
        internal static string UnsetAAfailed {
            get {
                return ResourceManager.GetString("UnsetAAfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivovanie a.zóny prebehlo úspešne.
        /// </summary>
        internal static string UnsetAAsucceeded {
            get {
                return ResourceManager.GetString("UnsetAAsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivovanie a. zón zlyhalo. Deaktivované a. zóny: {0}.
        /// </summary>
        internal static string UnsetFailure {
            get {
                return ResourceManager.GetString("UnsetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daktivovanie a. zón prebehlo úspešne.
        /// </summary>
        internal static string UnsetSuccess {
            get {
                return ResourceManager.GetString("UnsetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čaká sa na EIS.
        /// </summary>
        internal static string WaitingForEIS {
            get {
                return ResourceManager.GetString("WaitingForEIS", resourceCulture);
            }
        }
    }
}
